// This file was auto-generated by Fern from our API Definition.

package client

import (
	analytics "github.com/VapiAI/server-sdk-go/analytics"
	assistants "github.com/VapiAI/server-sdk-go/assistants"
	calls "github.com/VapiAI/server-sdk-go/calls"
	core "github.com/VapiAI/server-sdk-go/core"
	files "github.com/VapiAI/server-sdk-go/files"
	internal "github.com/VapiAI/server-sdk-go/internal"
	knowledgebases "github.com/VapiAI/server-sdk-go/knowledgebases"
	logs "github.com/VapiAI/server-sdk-go/logs"
	option "github.com/VapiAI/server-sdk-go/option"
	phonenumbers "github.com/VapiAI/server-sdk-go/phonenumbers"
	squads "github.com/VapiAI/server-sdk-go/squads"
	testsuiteruns "github.com/VapiAI/server-sdk-go/testsuiteruns"
	testsuites "github.com/VapiAI/server-sdk-go/testsuites"
	testsuitetests "github.com/VapiAI/server-sdk-go/testsuitetests"
	tools "github.com/VapiAI/server-sdk-go/tools"
	workflow "github.com/VapiAI/server-sdk-go/workflow"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Calls          *calls.Client
	Assistants     *assistants.Client
	PhoneNumbers   *phonenumbers.Client
	Tools          *tools.Client
	Files          *files.Client
	KnowledgeBases *knowledgebases.Client
	Workflow       *workflow.Client
	Squads         *squads.Client
	TestSuites     *testsuites.Client
	TestSuiteTests *testsuitetests.Client
	TestSuiteRuns  *testsuiteruns.Client
	Analytics      *analytics.Client
	Logs           *logs.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:         options.ToHeader(),
		Calls:          calls.NewClient(opts...),
		Assistants:     assistants.NewClient(opts...),
		PhoneNumbers:   phonenumbers.NewClient(opts...),
		Tools:          tools.NewClient(opts...),
		Files:          files.NewClient(opts...),
		KnowledgeBases: knowledgebases.NewClient(opts...),
		Workflow:       workflow.NewClient(opts...),
		Squads:         squads.NewClient(opts...),
		TestSuites:     testsuites.NewClient(opts...),
		TestSuiteTests: testsuitetests.NewClient(opts...),
		TestSuiteRuns:  testsuiteruns.NewClient(opts...),
		Analytics:      analytics.NewClient(opts...),
		Logs:           logs.NewClient(opts...),
	}
}
