// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	time "time"
)

type AssistantsListRequest struct {
	// This is the maximum number of items to return. Defaults to 100.
	Limit *float64 `json:"-" url:"limit,omitempty"`
	// This will return items where the createdAt is greater than the specified value.
	CreatedAtGt *time.Time `json:"-" url:"createdAtGt,omitempty"`
	// This will return items where the createdAt is less than the specified value.
	CreatedAtLt *time.Time `json:"-" url:"createdAtLt,omitempty"`
	// This will return items where the createdAt is greater than or equal to the specified value.
	CreatedAtGe *time.Time `json:"-" url:"createdAtGe,omitempty"`
	// This will return items where the createdAt is less than or equal to the specified value.
	CreatedAtLe *time.Time `json:"-" url:"createdAtLe,omitempty"`
	// This will return items where the updatedAt is greater than the specified value.
	UpdatedAtGt *time.Time `json:"-" url:"updatedAtGt,omitempty"`
	// This will return items where the updatedAt is less than the specified value.
	UpdatedAtLt *time.Time `json:"-" url:"updatedAtLt,omitempty"`
	// This will return items where the updatedAt is greater than or equal to the specified value.
	UpdatedAtGe *time.Time `json:"-" url:"updatedAtGe,omitempty"`
	// This will return items where the updatedAt is less than or equal to the specified value.
	UpdatedAtLe *time.Time `json:"-" url:"updatedAtLe,omitempty"`
}

// This is the background sound in the call. Default for phone calls is 'office' and default for web calls is 'off'.
// You can also provide a custom sound by providing a URL to an audio file.
type UpdateAssistantDtoBackgroundSound struct {
	UpdateAssistantDtoBackgroundSoundZero UpdateAssistantDtoBackgroundSoundZero
	String                                string

	typ string
}

func (u *UpdateAssistantDtoBackgroundSound) GetUpdateAssistantDtoBackgroundSoundZero() UpdateAssistantDtoBackgroundSoundZero {
	if u == nil {
		return ""
	}
	return u.UpdateAssistantDtoBackgroundSoundZero
}

func (u *UpdateAssistantDtoBackgroundSound) GetString() string {
	if u == nil {
		return ""
	}
	return u.String
}

func (u *UpdateAssistantDtoBackgroundSound) UnmarshalJSON(data []byte) error {
	var valueUpdateAssistantDtoBackgroundSoundZero UpdateAssistantDtoBackgroundSoundZero
	if err := json.Unmarshal(data, &valueUpdateAssistantDtoBackgroundSoundZero); err == nil {
		u.typ = "UpdateAssistantDtoBackgroundSoundZero"
		u.UpdateAssistantDtoBackgroundSoundZero = valueUpdateAssistantDtoBackgroundSoundZero
		return nil
	}
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		u.typ = "String"
		u.String = valueString
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, u)
}

func (u UpdateAssistantDtoBackgroundSound) MarshalJSON() ([]byte, error) {
	if u.typ == "UpdateAssistantDtoBackgroundSoundZero" || u.UpdateAssistantDtoBackgroundSoundZero != "" {
		return json.Marshal(u.UpdateAssistantDtoBackgroundSoundZero)
	}
	if u.typ == "String" || u.String != "" {
		return json.Marshal(u.String)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", u)
}

type UpdateAssistantDtoBackgroundSoundVisitor interface {
	VisitUpdateAssistantDtoBackgroundSoundZero(UpdateAssistantDtoBackgroundSoundZero) error
	VisitString(string) error
}

func (u *UpdateAssistantDtoBackgroundSound) Accept(visitor UpdateAssistantDtoBackgroundSoundVisitor) error {
	if u.typ == "UpdateAssistantDtoBackgroundSoundZero" || u.UpdateAssistantDtoBackgroundSoundZero != "" {
		return visitor.VisitUpdateAssistantDtoBackgroundSoundZero(u.UpdateAssistantDtoBackgroundSoundZero)
	}
	if u.typ == "String" || u.String != "" {
		return visitor.VisitString(u.String)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", u)
}

type UpdateAssistantDtoBackgroundSoundZero string

const (
	UpdateAssistantDtoBackgroundSoundZeroOff    UpdateAssistantDtoBackgroundSoundZero = "off"
	UpdateAssistantDtoBackgroundSoundZeroOffice UpdateAssistantDtoBackgroundSoundZero = "office"
)

func NewUpdateAssistantDtoBackgroundSoundZeroFromString(s string) (UpdateAssistantDtoBackgroundSoundZero, error) {
	switch s {
	case "off":
		return UpdateAssistantDtoBackgroundSoundZeroOff, nil
	case "office":
		return UpdateAssistantDtoBackgroundSoundZeroOffice, nil
	}
	var t UpdateAssistantDtoBackgroundSoundZero
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateAssistantDtoBackgroundSoundZero) Ptr() *UpdateAssistantDtoBackgroundSoundZero {
	return &u
}

type UpdateAssistantDtoClientMessagesItem string

const (
	UpdateAssistantDtoClientMessagesItemConversationUpdate  UpdateAssistantDtoClientMessagesItem = "conversation-update"
	UpdateAssistantDtoClientMessagesItemFunctionCall        UpdateAssistantDtoClientMessagesItem = "function-call"
	UpdateAssistantDtoClientMessagesItemFunctionCallResult  UpdateAssistantDtoClientMessagesItem = "function-call-result"
	UpdateAssistantDtoClientMessagesItemHang                UpdateAssistantDtoClientMessagesItem = "hang"
	UpdateAssistantDtoClientMessagesItemLanguageChanged     UpdateAssistantDtoClientMessagesItem = "language-changed"
	UpdateAssistantDtoClientMessagesItemMetadata            UpdateAssistantDtoClientMessagesItem = "metadata"
	UpdateAssistantDtoClientMessagesItemModelOutput         UpdateAssistantDtoClientMessagesItem = "model-output"
	UpdateAssistantDtoClientMessagesItemSpeechUpdate        UpdateAssistantDtoClientMessagesItem = "speech-update"
	UpdateAssistantDtoClientMessagesItemStatusUpdate        UpdateAssistantDtoClientMessagesItem = "status-update"
	UpdateAssistantDtoClientMessagesItemTranscript          UpdateAssistantDtoClientMessagesItem = "transcript"
	UpdateAssistantDtoClientMessagesItemToolCalls           UpdateAssistantDtoClientMessagesItem = "tool-calls"
	UpdateAssistantDtoClientMessagesItemToolCallsResult     UpdateAssistantDtoClientMessagesItem = "tool-calls-result"
	UpdateAssistantDtoClientMessagesItemToolCompleted       UpdateAssistantDtoClientMessagesItem = "tool.completed"
	UpdateAssistantDtoClientMessagesItemTransferUpdate      UpdateAssistantDtoClientMessagesItem = "transfer-update"
	UpdateAssistantDtoClientMessagesItemUserInterrupted     UpdateAssistantDtoClientMessagesItem = "user-interrupted"
	UpdateAssistantDtoClientMessagesItemVoiceInput          UpdateAssistantDtoClientMessagesItem = "voice-input"
	UpdateAssistantDtoClientMessagesItemWorkflowNodeStarted UpdateAssistantDtoClientMessagesItem = "workflow.node.started"
)

func NewUpdateAssistantDtoClientMessagesItemFromString(s string) (UpdateAssistantDtoClientMessagesItem, error) {
	switch s {
	case "conversation-update":
		return UpdateAssistantDtoClientMessagesItemConversationUpdate, nil
	case "function-call":
		return UpdateAssistantDtoClientMessagesItemFunctionCall, nil
	case "function-call-result":
		return UpdateAssistantDtoClientMessagesItemFunctionCallResult, nil
	case "hang":
		return UpdateAssistantDtoClientMessagesItemHang, nil
	case "language-changed":
		return UpdateAssistantDtoClientMessagesItemLanguageChanged, nil
	case "metadata":
		return UpdateAssistantDtoClientMessagesItemMetadata, nil
	case "model-output":
		return UpdateAssistantDtoClientMessagesItemModelOutput, nil
	case "speech-update":
		return UpdateAssistantDtoClientMessagesItemSpeechUpdate, nil
	case "status-update":
		return UpdateAssistantDtoClientMessagesItemStatusUpdate, nil
	case "transcript":
		return UpdateAssistantDtoClientMessagesItemTranscript, nil
	case "tool-calls":
		return UpdateAssistantDtoClientMessagesItemToolCalls, nil
	case "tool-calls-result":
		return UpdateAssistantDtoClientMessagesItemToolCallsResult, nil
	case "tool.completed":
		return UpdateAssistantDtoClientMessagesItemToolCompleted, nil
	case "transfer-update":
		return UpdateAssistantDtoClientMessagesItemTransferUpdate, nil
	case "user-interrupted":
		return UpdateAssistantDtoClientMessagesItemUserInterrupted, nil
	case "voice-input":
		return UpdateAssistantDtoClientMessagesItemVoiceInput, nil
	case "workflow.node.started":
		return UpdateAssistantDtoClientMessagesItemWorkflowNodeStarted, nil
	}
	var t UpdateAssistantDtoClientMessagesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateAssistantDtoClientMessagesItem) Ptr() *UpdateAssistantDtoClientMessagesItem {
	return &u
}

type UpdateAssistantDtoCredentialsItem struct {
	CreateElevenLabsCredentialDto                        *CreateElevenLabsCredentialDto
	CreateAnthropicCredentialDto                         *CreateAnthropicCredentialDto
	CreateAnyscaleCredentialDto                          *CreateAnyscaleCredentialDto
	CreateAssemblyAiCredentialDto                        *CreateAssemblyAiCredentialDto
	CreateAzureOpenAiCredentialDto                       *CreateAzureOpenAiCredentialDto
	CreateAzureCredentialDto                             *CreateAzureCredentialDto
	CreateByoSipTrunkCredentialDto                       *CreateByoSipTrunkCredentialDto
	CreateCartesiaCredentialDto                          *CreateCartesiaCredentialDto
	CreateCerebrasCredentialDto                          *CreateCerebrasCredentialDto
	CreateCloudflareCredentialDto                        *CreateCloudflareCredentialDto
	CreateCustomLlmCredentialDto                         *CreateCustomLlmCredentialDto
	CreateDeepgramCredentialDto                          *CreateDeepgramCredentialDto
	CreateDeepInfraCredentialDto                         *CreateDeepInfraCredentialDto
	CreateDeepSeekCredentialDto                          *CreateDeepSeekCredentialDto
	CreateGcpCredentialDto                               *CreateGcpCredentialDto
	CreateGladiaCredentialDto                            *CreateGladiaCredentialDto
	CreateGoHighLevelCredentialDto                       *CreateGoHighLevelCredentialDto
	CreateGoogleCredentialDto                            *CreateGoogleCredentialDto
	CreateGroqCredentialDto                              *CreateGroqCredentialDto
	CreateInflectionAiCredentialDto                      *CreateInflectionAiCredentialDto
	CreateLangfuseCredentialDto                          *CreateLangfuseCredentialDto
	CreateLmntCredentialDto                              *CreateLmntCredentialDto
	CreateMakeCredentialDto                              *CreateMakeCredentialDto
	CreateOpenAiCredentialDto                            *CreateOpenAiCredentialDto
	CreateOpenRouterCredentialDto                        *CreateOpenRouterCredentialDto
	CreatePerplexityAiCredentialDto                      *CreatePerplexityAiCredentialDto
	CreatePlayHtCredentialDto                            *CreatePlayHtCredentialDto
	CreateRimeAiCredentialDto                            *CreateRimeAiCredentialDto
	CreateRunpodCredentialDto                            *CreateRunpodCredentialDto
	CreateS3CredentialDto                                *CreateS3CredentialDto
	CreateSupabaseCredentialDto                          *CreateSupabaseCredentialDto
	CreateSmallestAiCredentialDto                        *CreateSmallestAiCredentialDto
	CreateTavusCredentialDto                             *CreateTavusCredentialDto
	CreateTogetherAiCredentialDto                        *CreateTogetherAiCredentialDto
	CreateTwilioCredentialDto                            *CreateTwilioCredentialDto
	CreateVonageCredentialDto                            *CreateVonageCredentialDto
	CreateWebhookCredentialDto                           *CreateWebhookCredentialDto
	CreateXAiCredentialDto                               *CreateXAiCredentialDto
	CreateNeuphonicCredentialDto                         *CreateNeuphonicCredentialDto
	CreateHumeCredentialDto                              *CreateHumeCredentialDto
	CreateMistralCredentialDto                           *CreateMistralCredentialDto
	CreateSpeechmaticsCredentialDto                      *CreateSpeechmaticsCredentialDto
	CreateTrieveCredentialDto                            *CreateTrieveCredentialDto
	CreateGoogleCalendarOAuth2ClientCredentialDto        *CreateGoogleCalendarOAuth2ClientCredentialDto
	CreateGoogleCalendarOAuth2AuthorizationCredentialDto *CreateGoogleCalendarOAuth2AuthorizationCredentialDto
	CreateGoogleSheetsOAuth2AuthorizationCredentialDto   *CreateGoogleSheetsOAuth2AuthorizationCredentialDto
	CreateSlackOAuth2AuthorizationCredentialDto          *CreateSlackOAuth2AuthorizationCredentialDto

	typ string
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateElevenLabsCredentialDto() *CreateElevenLabsCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateElevenLabsCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateAnthropicCredentialDto() *CreateAnthropicCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateAnthropicCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateAnyscaleCredentialDto() *CreateAnyscaleCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateAnyscaleCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateAssemblyAiCredentialDto() *CreateAssemblyAiCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateAssemblyAiCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateAzureOpenAiCredentialDto() *CreateAzureOpenAiCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateAzureOpenAiCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateAzureCredentialDto() *CreateAzureCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateAzureCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateByoSipTrunkCredentialDto() *CreateByoSipTrunkCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateByoSipTrunkCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateCartesiaCredentialDto() *CreateCartesiaCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateCartesiaCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateCerebrasCredentialDto() *CreateCerebrasCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateCerebrasCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateCloudflareCredentialDto() *CreateCloudflareCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateCloudflareCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateCustomLlmCredentialDto() *CreateCustomLlmCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateCustomLlmCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateDeepgramCredentialDto() *CreateDeepgramCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateDeepgramCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateDeepInfraCredentialDto() *CreateDeepInfraCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateDeepInfraCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateDeepSeekCredentialDto() *CreateDeepSeekCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateDeepSeekCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateGcpCredentialDto() *CreateGcpCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateGcpCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateGladiaCredentialDto() *CreateGladiaCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateGladiaCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateGoHighLevelCredentialDto() *CreateGoHighLevelCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateGoHighLevelCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateGoogleCredentialDto() *CreateGoogleCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateGoogleCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateGroqCredentialDto() *CreateGroqCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateGroqCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateInflectionAiCredentialDto() *CreateInflectionAiCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateInflectionAiCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateLangfuseCredentialDto() *CreateLangfuseCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateLangfuseCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateLmntCredentialDto() *CreateLmntCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateLmntCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateMakeCredentialDto() *CreateMakeCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateMakeCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateOpenAiCredentialDto() *CreateOpenAiCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateOpenAiCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateOpenRouterCredentialDto() *CreateOpenRouterCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateOpenRouterCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreatePerplexityAiCredentialDto() *CreatePerplexityAiCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreatePerplexityAiCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreatePlayHtCredentialDto() *CreatePlayHtCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreatePlayHtCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateRimeAiCredentialDto() *CreateRimeAiCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateRimeAiCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateRunpodCredentialDto() *CreateRunpodCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateRunpodCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateS3CredentialDto() *CreateS3CredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateS3CredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateSupabaseCredentialDto() *CreateSupabaseCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateSupabaseCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateSmallestAiCredentialDto() *CreateSmallestAiCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateSmallestAiCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateTavusCredentialDto() *CreateTavusCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateTavusCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateTogetherAiCredentialDto() *CreateTogetherAiCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateTogetherAiCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateTwilioCredentialDto() *CreateTwilioCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateTwilioCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateVonageCredentialDto() *CreateVonageCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateVonageCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateWebhookCredentialDto() *CreateWebhookCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateWebhookCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateXAiCredentialDto() *CreateXAiCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateXAiCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateNeuphonicCredentialDto() *CreateNeuphonicCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateNeuphonicCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateHumeCredentialDto() *CreateHumeCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateHumeCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateMistralCredentialDto() *CreateMistralCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateMistralCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateSpeechmaticsCredentialDto() *CreateSpeechmaticsCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateSpeechmaticsCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateTrieveCredentialDto() *CreateTrieveCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateTrieveCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateGoogleCalendarOAuth2ClientCredentialDto() *CreateGoogleCalendarOAuth2ClientCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateGoogleCalendarOAuth2ClientCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateGoogleCalendarOAuth2AuthorizationCredentialDto() *CreateGoogleCalendarOAuth2AuthorizationCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateGoogleCalendarOAuth2AuthorizationCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateGoogleSheetsOAuth2AuthorizationCredentialDto() *CreateGoogleSheetsOAuth2AuthorizationCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateGoogleSheetsOAuth2AuthorizationCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) GetCreateSlackOAuth2AuthorizationCredentialDto() *CreateSlackOAuth2AuthorizationCredentialDto {
	if u == nil {
		return nil
	}
	return u.CreateSlackOAuth2AuthorizationCredentialDto
}

func (u *UpdateAssistantDtoCredentialsItem) UnmarshalJSON(data []byte) error {
	valueCreateElevenLabsCredentialDto := new(CreateElevenLabsCredentialDto)
	if err := json.Unmarshal(data, &valueCreateElevenLabsCredentialDto); err == nil {
		u.typ = "CreateElevenLabsCredentialDto"
		u.CreateElevenLabsCredentialDto = valueCreateElevenLabsCredentialDto
		return nil
	}
	valueCreateAnthropicCredentialDto := new(CreateAnthropicCredentialDto)
	if err := json.Unmarshal(data, &valueCreateAnthropicCredentialDto); err == nil {
		u.typ = "CreateAnthropicCredentialDto"
		u.CreateAnthropicCredentialDto = valueCreateAnthropicCredentialDto
		return nil
	}
	valueCreateAnyscaleCredentialDto := new(CreateAnyscaleCredentialDto)
	if err := json.Unmarshal(data, &valueCreateAnyscaleCredentialDto); err == nil {
		u.typ = "CreateAnyscaleCredentialDto"
		u.CreateAnyscaleCredentialDto = valueCreateAnyscaleCredentialDto
		return nil
	}
	valueCreateAssemblyAiCredentialDto := new(CreateAssemblyAiCredentialDto)
	if err := json.Unmarshal(data, &valueCreateAssemblyAiCredentialDto); err == nil {
		u.typ = "CreateAssemblyAiCredentialDto"
		u.CreateAssemblyAiCredentialDto = valueCreateAssemblyAiCredentialDto
		return nil
	}
	valueCreateAzureOpenAiCredentialDto := new(CreateAzureOpenAiCredentialDto)
	if err := json.Unmarshal(data, &valueCreateAzureOpenAiCredentialDto); err == nil {
		u.typ = "CreateAzureOpenAiCredentialDto"
		u.CreateAzureOpenAiCredentialDto = valueCreateAzureOpenAiCredentialDto
		return nil
	}
	valueCreateAzureCredentialDto := new(CreateAzureCredentialDto)
	if err := json.Unmarshal(data, &valueCreateAzureCredentialDto); err == nil {
		u.typ = "CreateAzureCredentialDto"
		u.CreateAzureCredentialDto = valueCreateAzureCredentialDto
		return nil
	}
	valueCreateByoSipTrunkCredentialDto := new(CreateByoSipTrunkCredentialDto)
	if err := json.Unmarshal(data, &valueCreateByoSipTrunkCredentialDto); err == nil {
		u.typ = "CreateByoSipTrunkCredentialDto"
		u.CreateByoSipTrunkCredentialDto = valueCreateByoSipTrunkCredentialDto
		return nil
	}
	valueCreateCartesiaCredentialDto := new(CreateCartesiaCredentialDto)
	if err := json.Unmarshal(data, &valueCreateCartesiaCredentialDto); err == nil {
		u.typ = "CreateCartesiaCredentialDto"
		u.CreateCartesiaCredentialDto = valueCreateCartesiaCredentialDto
		return nil
	}
	valueCreateCerebrasCredentialDto := new(CreateCerebrasCredentialDto)
	if err := json.Unmarshal(data, &valueCreateCerebrasCredentialDto); err == nil {
		u.typ = "CreateCerebrasCredentialDto"
		u.CreateCerebrasCredentialDto = valueCreateCerebrasCredentialDto
		return nil
	}
	valueCreateCloudflareCredentialDto := new(CreateCloudflareCredentialDto)
	if err := json.Unmarshal(data, &valueCreateCloudflareCredentialDto); err == nil {
		u.typ = "CreateCloudflareCredentialDto"
		u.CreateCloudflareCredentialDto = valueCreateCloudflareCredentialDto
		return nil
	}
	valueCreateCustomLlmCredentialDto := new(CreateCustomLlmCredentialDto)
	if err := json.Unmarshal(data, &valueCreateCustomLlmCredentialDto); err == nil {
		u.typ = "CreateCustomLlmCredentialDto"
		u.CreateCustomLlmCredentialDto = valueCreateCustomLlmCredentialDto
		return nil
	}
	valueCreateDeepgramCredentialDto := new(CreateDeepgramCredentialDto)
	if err := json.Unmarshal(data, &valueCreateDeepgramCredentialDto); err == nil {
		u.typ = "CreateDeepgramCredentialDto"
		u.CreateDeepgramCredentialDto = valueCreateDeepgramCredentialDto
		return nil
	}
	valueCreateDeepInfraCredentialDto := new(CreateDeepInfraCredentialDto)
	if err := json.Unmarshal(data, &valueCreateDeepInfraCredentialDto); err == nil {
		u.typ = "CreateDeepInfraCredentialDto"
		u.CreateDeepInfraCredentialDto = valueCreateDeepInfraCredentialDto
		return nil
	}
	valueCreateDeepSeekCredentialDto := new(CreateDeepSeekCredentialDto)
	if err := json.Unmarshal(data, &valueCreateDeepSeekCredentialDto); err == nil {
		u.typ = "CreateDeepSeekCredentialDto"
		u.CreateDeepSeekCredentialDto = valueCreateDeepSeekCredentialDto
		return nil
	}
	valueCreateGcpCredentialDto := new(CreateGcpCredentialDto)
	if err := json.Unmarshal(data, &valueCreateGcpCredentialDto); err == nil {
		u.typ = "CreateGcpCredentialDto"
		u.CreateGcpCredentialDto = valueCreateGcpCredentialDto
		return nil
	}
	valueCreateGladiaCredentialDto := new(CreateGladiaCredentialDto)
	if err := json.Unmarshal(data, &valueCreateGladiaCredentialDto); err == nil {
		u.typ = "CreateGladiaCredentialDto"
		u.CreateGladiaCredentialDto = valueCreateGladiaCredentialDto
		return nil
	}
	valueCreateGoHighLevelCredentialDto := new(CreateGoHighLevelCredentialDto)
	if err := json.Unmarshal(data, &valueCreateGoHighLevelCredentialDto); err == nil {
		u.typ = "CreateGoHighLevelCredentialDto"
		u.CreateGoHighLevelCredentialDto = valueCreateGoHighLevelCredentialDto
		return nil
	}
	valueCreateGoogleCredentialDto := new(CreateGoogleCredentialDto)
	if err := json.Unmarshal(data, &valueCreateGoogleCredentialDto); err == nil {
		u.typ = "CreateGoogleCredentialDto"
		u.CreateGoogleCredentialDto = valueCreateGoogleCredentialDto
		return nil
	}
	valueCreateGroqCredentialDto := new(CreateGroqCredentialDto)
	if err := json.Unmarshal(data, &valueCreateGroqCredentialDto); err == nil {
		u.typ = "CreateGroqCredentialDto"
		u.CreateGroqCredentialDto = valueCreateGroqCredentialDto
		return nil
	}
	valueCreateInflectionAiCredentialDto := new(CreateInflectionAiCredentialDto)
	if err := json.Unmarshal(data, &valueCreateInflectionAiCredentialDto); err == nil {
		u.typ = "CreateInflectionAiCredentialDto"
		u.CreateInflectionAiCredentialDto = valueCreateInflectionAiCredentialDto
		return nil
	}
	valueCreateLangfuseCredentialDto := new(CreateLangfuseCredentialDto)
	if err := json.Unmarshal(data, &valueCreateLangfuseCredentialDto); err == nil {
		u.typ = "CreateLangfuseCredentialDto"
		u.CreateLangfuseCredentialDto = valueCreateLangfuseCredentialDto
		return nil
	}
	valueCreateLmntCredentialDto := new(CreateLmntCredentialDto)
	if err := json.Unmarshal(data, &valueCreateLmntCredentialDto); err == nil {
		u.typ = "CreateLmntCredentialDto"
		u.CreateLmntCredentialDto = valueCreateLmntCredentialDto
		return nil
	}
	valueCreateMakeCredentialDto := new(CreateMakeCredentialDto)
	if err := json.Unmarshal(data, &valueCreateMakeCredentialDto); err == nil {
		u.typ = "CreateMakeCredentialDto"
		u.CreateMakeCredentialDto = valueCreateMakeCredentialDto
		return nil
	}
	valueCreateOpenAiCredentialDto := new(CreateOpenAiCredentialDto)
	if err := json.Unmarshal(data, &valueCreateOpenAiCredentialDto); err == nil {
		u.typ = "CreateOpenAiCredentialDto"
		u.CreateOpenAiCredentialDto = valueCreateOpenAiCredentialDto
		return nil
	}
	valueCreateOpenRouterCredentialDto := new(CreateOpenRouterCredentialDto)
	if err := json.Unmarshal(data, &valueCreateOpenRouterCredentialDto); err == nil {
		u.typ = "CreateOpenRouterCredentialDto"
		u.CreateOpenRouterCredentialDto = valueCreateOpenRouterCredentialDto
		return nil
	}
	valueCreatePerplexityAiCredentialDto := new(CreatePerplexityAiCredentialDto)
	if err := json.Unmarshal(data, &valueCreatePerplexityAiCredentialDto); err == nil {
		u.typ = "CreatePerplexityAiCredentialDto"
		u.CreatePerplexityAiCredentialDto = valueCreatePerplexityAiCredentialDto
		return nil
	}
	valueCreatePlayHtCredentialDto := new(CreatePlayHtCredentialDto)
	if err := json.Unmarshal(data, &valueCreatePlayHtCredentialDto); err == nil {
		u.typ = "CreatePlayHtCredentialDto"
		u.CreatePlayHtCredentialDto = valueCreatePlayHtCredentialDto
		return nil
	}
	valueCreateRimeAiCredentialDto := new(CreateRimeAiCredentialDto)
	if err := json.Unmarshal(data, &valueCreateRimeAiCredentialDto); err == nil {
		u.typ = "CreateRimeAiCredentialDto"
		u.CreateRimeAiCredentialDto = valueCreateRimeAiCredentialDto
		return nil
	}
	valueCreateRunpodCredentialDto := new(CreateRunpodCredentialDto)
	if err := json.Unmarshal(data, &valueCreateRunpodCredentialDto); err == nil {
		u.typ = "CreateRunpodCredentialDto"
		u.CreateRunpodCredentialDto = valueCreateRunpodCredentialDto
		return nil
	}
	valueCreateS3CredentialDto := new(CreateS3CredentialDto)
	if err := json.Unmarshal(data, &valueCreateS3CredentialDto); err == nil {
		u.typ = "CreateS3CredentialDto"
		u.CreateS3CredentialDto = valueCreateS3CredentialDto
		return nil
	}
	valueCreateSupabaseCredentialDto := new(CreateSupabaseCredentialDto)
	if err := json.Unmarshal(data, &valueCreateSupabaseCredentialDto); err == nil {
		u.typ = "CreateSupabaseCredentialDto"
		u.CreateSupabaseCredentialDto = valueCreateSupabaseCredentialDto
		return nil
	}
	valueCreateSmallestAiCredentialDto := new(CreateSmallestAiCredentialDto)
	if err := json.Unmarshal(data, &valueCreateSmallestAiCredentialDto); err == nil {
		u.typ = "CreateSmallestAiCredentialDto"
		u.CreateSmallestAiCredentialDto = valueCreateSmallestAiCredentialDto
		return nil
	}
	valueCreateTavusCredentialDto := new(CreateTavusCredentialDto)
	if err := json.Unmarshal(data, &valueCreateTavusCredentialDto); err == nil {
		u.typ = "CreateTavusCredentialDto"
		u.CreateTavusCredentialDto = valueCreateTavusCredentialDto
		return nil
	}
	valueCreateTogetherAiCredentialDto := new(CreateTogetherAiCredentialDto)
	if err := json.Unmarshal(data, &valueCreateTogetherAiCredentialDto); err == nil {
		u.typ = "CreateTogetherAiCredentialDto"
		u.CreateTogetherAiCredentialDto = valueCreateTogetherAiCredentialDto
		return nil
	}
	valueCreateTwilioCredentialDto := new(CreateTwilioCredentialDto)
	if err := json.Unmarshal(data, &valueCreateTwilioCredentialDto); err == nil {
		u.typ = "CreateTwilioCredentialDto"
		u.CreateTwilioCredentialDto = valueCreateTwilioCredentialDto
		return nil
	}
	valueCreateVonageCredentialDto := new(CreateVonageCredentialDto)
	if err := json.Unmarshal(data, &valueCreateVonageCredentialDto); err == nil {
		u.typ = "CreateVonageCredentialDto"
		u.CreateVonageCredentialDto = valueCreateVonageCredentialDto
		return nil
	}
	valueCreateWebhookCredentialDto := new(CreateWebhookCredentialDto)
	if err := json.Unmarshal(data, &valueCreateWebhookCredentialDto); err == nil {
		u.typ = "CreateWebhookCredentialDto"
		u.CreateWebhookCredentialDto = valueCreateWebhookCredentialDto
		return nil
	}
	valueCreateXAiCredentialDto := new(CreateXAiCredentialDto)
	if err := json.Unmarshal(data, &valueCreateXAiCredentialDto); err == nil {
		u.typ = "CreateXAiCredentialDto"
		u.CreateXAiCredentialDto = valueCreateXAiCredentialDto
		return nil
	}
	valueCreateNeuphonicCredentialDto := new(CreateNeuphonicCredentialDto)
	if err := json.Unmarshal(data, &valueCreateNeuphonicCredentialDto); err == nil {
		u.typ = "CreateNeuphonicCredentialDto"
		u.CreateNeuphonicCredentialDto = valueCreateNeuphonicCredentialDto
		return nil
	}
	valueCreateHumeCredentialDto := new(CreateHumeCredentialDto)
	if err := json.Unmarshal(data, &valueCreateHumeCredentialDto); err == nil {
		u.typ = "CreateHumeCredentialDto"
		u.CreateHumeCredentialDto = valueCreateHumeCredentialDto
		return nil
	}
	valueCreateMistralCredentialDto := new(CreateMistralCredentialDto)
	if err := json.Unmarshal(data, &valueCreateMistralCredentialDto); err == nil {
		u.typ = "CreateMistralCredentialDto"
		u.CreateMistralCredentialDto = valueCreateMistralCredentialDto
		return nil
	}
	valueCreateSpeechmaticsCredentialDto := new(CreateSpeechmaticsCredentialDto)
	if err := json.Unmarshal(data, &valueCreateSpeechmaticsCredentialDto); err == nil {
		u.typ = "CreateSpeechmaticsCredentialDto"
		u.CreateSpeechmaticsCredentialDto = valueCreateSpeechmaticsCredentialDto
		return nil
	}
	valueCreateTrieveCredentialDto := new(CreateTrieveCredentialDto)
	if err := json.Unmarshal(data, &valueCreateTrieveCredentialDto); err == nil {
		u.typ = "CreateTrieveCredentialDto"
		u.CreateTrieveCredentialDto = valueCreateTrieveCredentialDto
		return nil
	}
	valueCreateGoogleCalendarOAuth2ClientCredentialDto := new(CreateGoogleCalendarOAuth2ClientCredentialDto)
	if err := json.Unmarshal(data, &valueCreateGoogleCalendarOAuth2ClientCredentialDto); err == nil {
		u.typ = "CreateGoogleCalendarOAuth2ClientCredentialDto"
		u.CreateGoogleCalendarOAuth2ClientCredentialDto = valueCreateGoogleCalendarOAuth2ClientCredentialDto
		return nil
	}
	valueCreateGoogleCalendarOAuth2AuthorizationCredentialDto := new(CreateGoogleCalendarOAuth2AuthorizationCredentialDto)
	if err := json.Unmarshal(data, &valueCreateGoogleCalendarOAuth2AuthorizationCredentialDto); err == nil {
		u.typ = "CreateGoogleCalendarOAuth2AuthorizationCredentialDto"
		u.CreateGoogleCalendarOAuth2AuthorizationCredentialDto = valueCreateGoogleCalendarOAuth2AuthorizationCredentialDto
		return nil
	}
	valueCreateGoogleSheetsOAuth2AuthorizationCredentialDto := new(CreateGoogleSheetsOAuth2AuthorizationCredentialDto)
	if err := json.Unmarshal(data, &valueCreateGoogleSheetsOAuth2AuthorizationCredentialDto); err == nil {
		u.typ = "CreateGoogleSheetsOAuth2AuthorizationCredentialDto"
		u.CreateGoogleSheetsOAuth2AuthorizationCredentialDto = valueCreateGoogleSheetsOAuth2AuthorizationCredentialDto
		return nil
	}
	valueCreateSlackOAuth2AuthorizationCredentialDto := new(CreateSlackOAuth2AuthorizationCredentialDto)
	if err := json.Unmarshal(data, &valueCreateSlackOAuth2AuthorizationCredentialDto); err == nil {
		u.typ = "CreateSlackOAuth2AuthorizationCredentialDto"
		u.CreateSlackOAuth2AuthorizationCredentialDto = valueCreateSlackOAuth2AuthorizationCredentialDto
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, u)
}

func (u UpdateAssistantDtoCredentialsItem) MarshalJSON() ([]byte, error) {
	if u.typ == "CreateElevenLabsCredentialDto" || u.CreateElevenLabsCredentialDto != nil {
		return json.Marshal(u.CreateElevenLabsCredentialDto)
	}
	if u.typ == "CreateAnthropicCredentialDto" || u.CreateAnthropicCredentialDto != nil {
		return json.Marshal(u.CreateAnthropicCredentialDto)
	}
	if u.typ == "CreateAnyscaleCredentialDto" || u.CreateAnyscaleCredentialDto != nil {
		return json.Marshal(u.CreateAnyscaleCredentialDto)
	}
	if u.typ == "CreateAssemblyAiCredentialDto" || u.CreateAssemblyAiCredentialDto != nil {
		return json.Marshal(u.CreateAssemblyAiCredentialDto)
	}
	if u.typ == "CreateAzureOpenAiCredentialDto" || u.CreateAzureOpenAiCredentialDto != nil {
		return json.Marshal(u.CreateAzureOpenAiCredentialDto)
	}
	if u.typ == "CreateAzureCredentialDto" || u.CreateAzureCredentialDto != nil {
		return json.Marshal(u.CreateAzureCredentialDto)
	}
	if u.typ == "CreateByoSipTrunkCredentialDto" || u.CreateByoSipTrunkCredentialDto != nil {
		return json.Marshal(u.CreateByoSipTrunkCredentialDto)
	}
	if u.typ == "CreateCartesiaCredentialDto" || u.CreateCartesiaCredentialDto != nil {
		return json.Marshal(u.CreateCartesiaCredentialDto)
	}
	if u.typ == "CreateCerebrasCredentialDto" || u.CreateCerebrasCredentialDto != nil {
		return json.Marshal(u.CreateCerebrasCredentialDto)
	}
	if u.typ == "CreateCloudflareCredentialDto" || u.CreateCloudflareCredentialDto != nil {
		return json.Marshal(u.CreateCloudflareCredentialDto)
	}
	if u.typ == "CreateCustomLlmCredentialDto" || u.CreateCustomLlmCredentialDto != nil {
		return json.Marshal(u.CreateCustomLlmCredentialDto)
	}
	if u.typ == "CreateDeepgramCredentialDto" || u.CreateDeepgramCredentialDto != nil {
		return json.Marshal(u.CreateDeepgramCredentialDto)
	}
	if u.typ == "CreateDeepInfraCredentialDto" || u.CreateDeepInfraCredentialDto != nil {
		return json.Marshal(u.CreateDeepInfraCredentialDto)
	}
	if u.typ == "CreateDeepSeekCredentialDto" || u.CreateDeepSeekCredentialDto != nil {
		return json.Marshal(u.CreateDeepSeekCredentialDto)
	}
	if u.typ == "CreateGcpCredentialDto" || u.CreateGcpCredentialDto != nil {
		return json.Marshal(u.CreateGcpCredentialDto)
	}
	if u.typ == "CreateGladiaCredentialDto" || u.CreateGladiaCredentialDto != nil {
		return json.Marshal(u.CreateGladiaCredentialDto)
	}
	if u.typ == "CreateGoHighLevelCredentialDto" || u.CreateGoHighLevelCredentialDto != nil {
		return json.Marshal(u.CreateGoHighLevelCredentialDto)
	}
	if u.typ == "CreateGoogleCredentialDto" || u.CreateGoogleCredentialDto != nil {
		return json.Marshal(u.CreateGoogleCredentialDto)
	}
	if u.typ == "CreateGroqCredentialDto" || u.CreateGroqCredentialDto != nil {
		return json.Marshal(u.CreateGroqCredentialDto)
	}
	if u.typ == "CreateInflectionAiCredentialDto" || u.CreateInflectionAiCredentialDto != nil {
		return json.Marshal(u.CreateInflectionAiCredentialDto)
	}
	if u.typ == "CreateLangfuseCredentialDto" || u.CreateLangfuseCredentialDto != nil {
		return json.Marshal(u.CreateLangfuseCredentialDto)
	}
	if u.typ == "CreateLmntCredentialDto" || u.CreateLmntCredentialDto != nil {
		return json.Marshal(u.CreateLmntCredentialDto)
	}
	if u.typ == "CreateMakeCredentialDto" || u.CreateMakeCredentialDto != nil {
		return json.Marshal(u.CreateMakeCredentialDto)
	}
	if u.typ == "CreateOpenAiCredentialDto" || u.CreateOpenAiCredentialDto != nil {
		return json.Marshal(u.CreateOpenAiCredentialDto)
	}
	if u.typ == "CreateOpenRouterCredentialDto" || u.CreateOpenRouterCredentialDto != nil {
		return json.Marshal(u.CreateOpenRouterCredentialDto)
	}
	if u.typ == "CreatePerplexityAiCredentialDto" || u.CreatePerplexityAiCredentialDto != nil {
		return json.Marshal(u.CreatePerplexityAiCredentialDto)
	}
	if u.typ == "CreatePlayHtCredentialDto" || u.CreatePlayHtCredentialDto != nil {
		return json.Marshal(u.CreatePlayHtCredentialDto)
	}
	if u.typ == "CreateRimeAiCredentialDto" || u.CreateRimeAiCredentialDto != nil {
		return json.Marshal(u.CreateRimeAiCredentialDto)
	}
	if u.typ == "CreateRunpodCredentialDto" || u.CreateRunpodCredentialDto != nil {
		return json.Marshal(u.CreateRunpodCredentialDto)
	}
	if u.typ == "CreateS3CredentialDto" || u.CreateS3CredentialDto != nil {
		return json.Marshal(u.CreateS3CredentialDto)
	}
	if u.typ == "CreateSupabaseCredentialDto" || u.CreateSupabaseCredentialDto != nil {
		return json.Marshal(u.CreateSupabaseCredentialDto)
	}
	if u.typ == "CreateSmallestAiCredentialDto" || u.CreateSmallestAiCredentialDto != nil {
		return json.Marshal(u.CreateSmallestAiCredentialDto)
	}
	if u.typ == "CreateTavusCredentialDto" || u.CreateTavusCredentialDto != nil {
		return json.Marshal(u.CreateTavusCredentialDto)
	}
	if u.typ == "CreateTogetherAiCredentialDto" || u.CreateTogetherAiCredentialDto != nil {
		return json.Marshal(u.CreateTogetherAiCredentialDto)
	}
	if u.typ == "CreateTwilioCredentialDto" || u.CreateTwilioCredentialDto != nil {
		return json.Marshal(u.CreateTwilioCredentialDto)
	}
	if u.typ == "CreateVonageCredentialDto" || u.CreateVonageCredentialDto != nil {
		return json.Marshal(u.CreateVonageCredentialDto)
	}
	if u.typ == "CreateWebhookCredentialDto" || u.CreateWebhookCredentialDto != nil {
		return json.Marshal(u.CreateWebhookCredentialDto)
	}
	if u.typ == "CreateXAiCredentialDto" || u.CreateXAiCredentialDto != nil {
		return json.Marshal(u.CreateXAiCredentialDto)
	}
	if u.typ == "CreateNeuphonicCredentialDto" || u.CreateNeuphonicCredentialDto != nil {
		return json.Marshal(u.CreateNeuphonicCredentialDto)
	}
	if u.typ == "CreateHumeCredentialDto" || u.CreateHumeCredentialDto != nil {
		return json.Marshal(u.CreateHumeCredentialDto)
	}
	if u.typ == "CreateMistralCredentialDto" || u.CreateMistralCredentialDto != nil {
		return json.Marshal(u.CreateMistralCredentialDto)
	}
	if u.typ == "CreateSpeechmaticsCredentialDto" || u.CreateSpeechmaticsCredentialDto != nil {
		return json.Marshal(u.CreateSpeechmaticsCredentialDto)
	}
	if u.typ == "CreateTrieveCredentialDto" || u.CreateTrieveCredentialDto != nil {
		return json.Marshal(u.CreateTrieveCredentialDto)
	}
	if u.typ == "CreateGoogleCalendarOAuth2ClientCredentialDto" || u.CreateGoogleCalendarOAuth2ClientCredentialDto != nil {
		return json.Marshal(u.CreateGoogleCalendarOAuth2ClientCredentialDto)
	}
	if u.typ == "CreateGoogleCalendarOAuth2AuthorizationCredentialDto" || u.CreateGoogleCalendarOAuth2AuthorizationCredentialDto != nil {
		return json.Marshal(u.CreateGoogleCalendarOAuth2AuthorizationCredentialDto)
	}
	if u.typ == "CreateGoogleSheetsOAuth2AuthorizationCredentialDto" || u.CreateGoogleSheetsOAuth2AuthorizationCredentialDto != nil {
		return json.Marshal(u.CreateGoogleSheetsOAuth2AuthorizationCredentialDto)
	}
	if u.typ == "CreateSlackOAuth2AuthorizationCredentialDto" || u.CreateSlackOAuth2AuthorizationCredentialDto != nil {
		return json.Marshal(u.CreateSlackOAuth2AuthorizationCredentialDto)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", u)
}

type UpdateAssistantDtoCredentialsItemVisitor interface {
	VisitCreateElevenLabsCredentialDto(*CreateElevenLabsCredentialDto) error
	VisitCreateAnthropicCredentialDto(*CreateAnthropicCredentialDto) error
	VisitCreateAnyscaleCredentialDto(*CreateAnyscaleCredentialDto) error
	VisitCreateAssemblyAiCredentialDto(*CreateAssemblyAiCredentialDto) error
	VisitCreateAzureOpenAiCredentialDto(*CreateAzureOpenAiCredentialDto) error
	VisitCreateAzureCredentialDto(*CreateAzureCredentialDto) error
	VisitCreateByoSipTrunkCredentialDto(*CreateByoSipTrunkCredentialDto) error
	VisitCreateCartesiaCredentialDto(*CreateCartesiaCredentialDto) error
	VisitCreateCerebrasCredentialDto(*CreateCerebrasCredentialDto) error
	VisitCreateCloudflareCredentialDto(*CreateCloudflareCredentialDto) error
	VisitCreateCustomLlmCredentialDto(*CreateCustomLlmCredentialDto) error
	VisitCreateDeepgramCredentialDto(*CreateDeepgramCredentialDto) error
	VisitCreateDeepInfraCredentialDto(*CreateDeepInfraCredentialDto) error
	VisitCreateDeepSeekCredentialDto(*CreateDeepSeekCredentialDto) error
	VisitCreateGcpCredentialDto(*CreateGcpCredentialDto) error
	VisitCreateGladiaCredentialDto(*CreateGladiaCredentialDto) error
	VisitCreateGoHighLevelCredentialDto(*CreateGoHighLevelCredentialDto) error
	VisitCreateGoogleCredentialDto(*CreateGoogleCredentialDto) error
	VisitCreateGroqCredentialDto(*CreateGroqCredentialDto) error
	VisitCreateInflectionAiCredentialDto(*CreateInflectionAiCredentialDto) error
	VisitCreateLangfuseCredentialDto(*CreateLangfuseCredentialDto) error
	VisitCreateLmntCredentialDto(*CreateLmntCredentialDto) error
	VisitCreateMakeCredentialDto(*CreateMakeCredentialDto) error
	VisitCreateOpenAiCredentialDto(*CreateOpenAiCredentialDto) error
	VisitCreateOpenRouterCredentialDto(*CreateOpenRouterCredentialDto) error
	VisitCreatePerplexityAiCredentialDto(*CreatePerplexityAiCredentialDto) error
	VisitCreatePlayHtCredentialDto(*CreatePlayHtCredentialDto) error
	VisitCreateRimeAiCredentialDto(*CreateRimeAiCredentialDto) error
	VisitCreateRunpodCredentialDto(*CreateRunpodCredentialDto) error
	VisitCreateS3CredentialDto(*CreateS3CredentialDto) error
	VisitCreateSupabaseCredentialDto(*CreateSupabaseCredentialDto) error
	VisitCreateSmallestAiCredentialDto(*CreateSmallestAiCredentialDto) error
	VisitCreateTavusCredentialDto(*CreateTavusCredentialDto) error
	VisitCreateTogetherAiCredentialDto(*CreateTogetherAiCredentialDto) error
	VisitCreateTwilioCredentialDto(*CreateTwilioCredentialDto) error
	VisitCreateVonageCredentialDto(*CreateVonageCredentialDto) error
	VisitCreateWebhookCredentialDto(*CreateWebhookCredentialDto) error
	VisitCreateXAiCredentialDto(*CreateXAiCredentialDto) error
	VisitCreateNeuphonicCredentialDto(*CreateNeuphonicCredentialDto) error
	VisitCreateHumeCredentialDto(*CreateHumeCredentialDto) error
	VisitCreateMistralCredentialDto(*CreateMistralCredentialDto) error
	VisitCreateSpeechmaticsCredentialDto(*CreateSpeechmaticsCredentialDto) error
	VisitCreateTrieveCredentialDto(*CreateTrieveCredentialDto) error
	VisitCreateGoogleCalendarOAuth2ClientCredentialDto(*CreateGoogleCalendarOAuth2ClientCredentialDto) error
	VisitCreateGoogleCalendarOAuth2AuthorizationCredentialDto(*CreateGoogleCalendarOAuth2AuthorizationCredentialDto) error
	VisitCreateGoogleSheetsOAuth2AuthorizationCredentialDto(*CreateGoogleSheetsOAuth2AuthorizationCredentialDto) error
	VisitCreateSlackOAuth2AuthorizationCredentialDto(*CreateSlackOAuth2AuthorizationCredentialDto) error
}

func (u *UpdateAssistantDtoCredentialsItem) Accept(visitor UpdateAssistantDtoCredentialsItemVisitor) error {
	if u.typ == "CreateElevenLabsCredentialDto" || u.CreateElevenLabsCredentialDto != nil {
		return visitor.VisitCreateElevenLabsCredentialDto(u.CreateElevenLabsCredentialDto)
	}
	if u.typ == "CreateAnthropicCredentialDto" || u.CreateAnthropicCredentialDto != nil {
		return visitor.VisitCreateAnthropicCredentialDto(u.CreateAnthropicCredentialDto)
	}
	if u.typ == "CreateAnyscaleCredentialDto" || u.CreateAnyscaleCredentialDto != nil {
		return visitor.VisitCreateAnyscaleCredentialDto(u.CreateAnyscaleCredentialDto)
	}
	if u.typ == "CreateAssemblyAiCredentialDto" || u.CreateAssemblyAiCredentialDto != nil {
		return visitor.VisitCreateAssemblyAiCredentialDto(u.CreateAssemblyAiCredentialDto)
	}
	if u.typ == "CreateAzureOpenAiCredentialDto" || u.CreateAzureOpenAiCredentialDto != nil {
		return visitor.VisitCreateAzureOpenAiCredentialDto(u.CreateAzureOpenAiCredentialDto)
	}
	if u.typ == "CreateAzureCredentialDto" || u.CreateAzureCredentialDto != nil {
		return visitor.VisitCreateAzureCredentialDto(u.CreateAzureCredentialDto)
	}
	if u.typ == "CreateByoSipTrunkCredentialDto" || u.CreateByoSipTrunkCredentialDto != nil {
		return visitor.VisitCreateByoSipTrunkCredentialDto(u.CreateByoSipTrunkCredentialDto)
	}
	if u.typ == "CreateCartesiaCredentialDto" || u.CreateCartesiaCredentialDto != nil {
		return visitor.VisitCreateCartesiaCredentialDto(u.CreateCartesiaCredentialDto)
	}
	if u.typ == "CreateCerebrasCredentialDto" || u.CreateCerebrasCredentialDto != nil {
		return visitor.VisitCreateCerebrasCredentialDto(u.CreateCerebrasCredentialDto)
	}
	if u.typ == "CreateCloudflareCredentialDto" || u.CreateCloudflareCredentialDto != nil {
		return visitor.VisitCreateCloudflareCredentialDto(u.CreateCloudflareCredentialDto)
	}
	if u.typ == "CreateCustomLlmCredentialDto" || u.CreateCustomLlmCredentialDto != nil {
		return visitor.VisitCreateCustomLlmCredentialDto(u.CreateCustomLlmCredentialDto)
	}
	if u.typ == "CreateDeepgramCredentialDto" || u.CreateDeepgramCredentialDto != nil {
		return visitor.VisitCreateDeepgramCredentialDto(u.CreateDeepgramCredentialDto)
	}
	if u.typ == "CreateDeepInfraCredentialDto" || u.CreateDeepInfraCredentialDto != nil {
		return visitor.VisitCreateDeepInfraCredentialDto(u.CreateDeepInfraCredentialDto)
	}
	if u.typ == "CreateDeepSeekCredentialDto" || u.CreateDeepSeekCredentialDto != nil {
		return visitor.VisitCreateDeepSeekCredentialDto(u.CreateDeepSeekCredentialDto)
	}
	if u.typ == "CreateGcpCredentialDto" || u.CreateGcpCredentialDto != nil {
		return visitor.VisitCreateGcpCredentialDto(u.CreateGcpCredentialDto)
	}
	if u.typ == "CreateGladiaCredentialDto" || u.CreateGladiaCredentialDto != nil {
		return visitor.VisitCreateGladiaCredentialDto(u.CreateGladiaCredentialDto)
	}
	if u.typ == "CreateGoHighLevelCredentialDto" || u.CreateGoHighLevelCredentialDto != nil {
		return visitor.VisitCreateGoHighLevelCredentialDto(u.CreateGoHighLevelCredentialDto)
	}
	if u.typ == "CreateGoogleCredentialDto" || u.CreateGoogleCredentialDto != nil {
		return visitor.VisitCreateGoogleCredentialDto(u.CreateGoogleCredentialDto)
	}
	if u.typ == "CreateGroqCredentialDto" || u.CreateGroqCredentialDto != nil {
		return visitor.VisitCreateGroqCredentialDto(u.CreateGroqCredentialDto)
	}
	if u.typ == "CreateInflectionAiCredentialDto" || u.CreateInflectionAiCredentialDto != nil {
		return visitor.VisitCreateInflectionAiCredentialDto(u.CreateInflectionAiCredentialDto)
	}
	if u.typ == "CreateLangfuseCredentialDto" || u.CreateLangfuseCredentialDto != nil {
		return visitor.VisitCreateLangfuseCredentialDto(u.CreateLangfuseCredentialDto)
	}
	if u.typ == "CreateLmntCredentialDto" || u.CreateLmntCredentialDto != nil {
		return visitor.VisitCreateLmntCredentialDto(u.CreateLmntCredentialDto)
	}
	if u.typ == "CreateMakeCredentialDto" || u.CreateMakeCredentialDto != nil {
		return visitor.VisitCreateMakeCredentialDto(u.CreateMakeCredentialDto)
	}
	if u.typ == "CreateOpenAiCredentialDto" || u.CreateOpenAiCredentialDto != nil {
		return visitor.VisitCreateOpenAiCredentialDto(u.CreateOpenAiCredentialDto)
	}
	if u.typ == "CreateOpenRouterCredentialDto" || u.CreateOpenRouterCredentialDto != nil {
		return visitor.VisitCreateOpenRouterCredentialDto(u.CreateOpenRouterCredentialDto)
	}
	if u.typ == "CreatePerplexityAiCredentialDto" || u.CreatePerplexityAiCredentialDto != nil {
		return visitor.VisitCreatePerplexityAiCredentialDto(u.CreatePerplexityAiCredentialDto)
	}
	if u.typ == "CreatePlayHtCredentialDto" || u.CreatePlayHtCredentialDto != nil {
		return visitor.VisitCreatePlayHtCredentialDto(u.CreatePlayHtCredentialDto)
	}
	if u.typ == "CreateRimeAiCredentialDto" || u.CreateRimeAiCredentialDto != nil {
		return visitor.VisitCreateRimeAiCredentialDto(u.CreateRimeAiCredentialDto)
	}
	if u.typ == "CreateRunpodCredentialDto" || u.CreateRunpodCredentialDto != nil {
		return visitor.VisitCreateRunpodCredentialDto(u.CreateRunpodCredentialDto)
	}
	if u.typ == "CreateS3CredentialDto" || u.CreateS3CredentialDto != nil {
		return visitor.VisitCreateS3CredentialDto(u.CreateS3CredentialDto)
	}
	if u.typ == "CreateSupabaseCredentialDto" || u.CreateSupabaseCredentialDto != nil {
		return visitor.VisitCreateSupabaseCredentialDto(u.CreateSupabaseCredentialDto)
	}
	if u.typ == "CreateSmallestAiCredentialDto" || u.CreateSmallestAiCredentialDto != nil {
		return visitor.VisitCreateSmallestAiCredentialDto(u.CreateSmallestAiCredentialDto)
	}
	if u.typ == "CreateTavusCredentialDto" || u.CreateTavusCredentialDto != nil {
		return visitor.VisitCreateTavusCredentialDto(u.CreateTavusCredentialDto)
	}
	if u.typ == "CreateTogetherAiCredentialDto" || u.CreateTogetherAiCredentialDto != nil {
		return visitor.VisitCreateTogetherAiCredentialDto(u.CreateTogetherAiCredentialDto)
	}
	if u.typ == "CreateTwilioCredentialDto" || u.CreateTwilioCredentialDto != nil {
		return visitor.VisitCreateTwilioCredentialDto(u.CreateTwilioCredentialDto)
	}
	if u.typ == "CreateVonageCredentialDto" || u.CreateVonageCredentialDto != nil {
		return visitor.VisitCreateVonageCredentialDto(u.CreateVonageCredentialDto)
	}
	if u.typ == "CreateWebhookCredentialDto" || u.CreateWebhookCredentialDto != nil {
		return visitor.VisitCreateWebhookCredentialDto(u.CreateWebhookCredentialDto)
	}
	if u.typ == "CreateXAiCredentialDto" || u.CreateXAiCredentialDto != nil {
		return visitor.VisitCreateXAiCredentialDto(u.CreateXAiCredentialDto)
	}
	if u.typ == "CreateNeuphonicCredentialDto" || u.CreateNeuphonicCredentialDto != nil {
		return visitor.VisitCreateNeuphonicCredentialDto(u.CreateNeuphonicCredentialDto)
	}
	if u.typ == "CreateHumeCredentialDto" || u.CreateHumeCredentialDto != nil {
		return visitor.VisitCreateHumeCredentialDto(u.CreateHumeCredentialDto)
	}
	if u.typ == "CreateMistralCredentialDto" || u.CreateMistralCredentialDto != nil {
		return visitor.VisitCreateMistralCredentialDto(u.CreateMistralCredentialDto)
	}
	if u.typ == "CreateSpeechmaticsCredentialDto" || u.CreateSpeechmaticsCredentialDto != nil {
		return visitor.VisitCreateSpeechmaticsCredentialDto(u.CreateSpeechmaticsCredentialDto)
	}
	if u.typ == "CreateTrieveCredentialDto" || u.CreateTrieveCredentialDto != nil {
		return visitor.VisitCreateTrieveCredentialDto(u.CreateTrieveCredentialDto)
	}
	if u.typ == "CreateGoogleCalendarOAuth2ClientCredentialDto" || u.CreateGoogleCalendarOAuth2ClientCredentialDto != nil {
		return visitor.VisitCreateGoogleCalendarOAuth2ClientCredentialDto(u.CreateGoogleCalendarOAuth2ClientCredentialDto)
	}
	if u.typ == "CreateGoogleCalendarOAuth2AuthorizationCredentialDto" || u.CreateGoogleCalendarOAuth2AuthorizationCredentialDto != nil {
		return visitor.VisitCreateGoogleCalendarOAuth2AuthorizationCredentialDto(u.CreateGoogleCalendarOAuth2AuthorizationCredentialDto)
	}
	if u.typ == "CreateGoogleSheetsOAuth2AuthorizationCredentialDto" || u.CreateGoogleSheetsOAuth2AuthorizationCredentialDto != nil {
		return visitor.VisitCreateGoogleSheetsOAuth2AuthorizationCredentialDto(u.CreateGoogleSheetsOAuth2AuthorizationCredentialDto)
	}
	if u.typ == "CreateSlackOAuth2AuthorizationCredentialDto" || u.CreateSlackOAuth2AuthorizationCredentialDto != nil {
		return visitor.VisitCreateSlackOAuth2AuthorizationCredentialDto(u.CreateSlackOAuth2AuthorizationCredentialDto)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", u)
}

// This is the mode for the first message. Default is 'assistant-speaks-first'.
//
// Use:
// - 'assistant-speaks-first' to have the assistant speak first.
// - 'assistant-waits-for-user' to have the assistant wait for the user to speak first.
// - 'assistant-speaks-first-with-model-generated-message' to have the assistant speak first with a message generated by the model based on the conversation state. (`assistant.model.messages` at call start, `call.messages` at squad transfer points).
//
// @default 'assistant-speaks-first'
type UpdateAssistantDtoFirstMessageMode string

const (
	UpdateAssistantDtoFirstMessageModeAssistantSpeaksFirst                          UpdateAssistantDtoFirstMessageMode = "assistant-speaks-first"
	UpdateAssistantDtoFirstMessageModeAssistantSpeaksFirstWithModelGeneratedMessage UpdateAssistantDtoFirstMessageMode = "assistant-speaks-first-with-model-generated-message"
	UpdateAssistantDtoFirstMessageModeAssistantWaitsForUser                         UpdateAssistantDtoFirstMessageMode = "assistant-waits-for-user"
)

func NewUpdateAssistantDtoFirstMessageModeFromString(s string) (UpdateAssistantDtoFirstMessageMode, error) {
	switch s {
	case "assistant-speaks-first":
		return UpdateAssistantDtoFirstMessageModeAssistantSpeaksFirst, nil
	case "assistant-speaks-first-with-model-generated-message":
		return UpdateAssistantDtoFirstMessageModeAssistantSpeaksFirstWithModelGeneratedMessage, nil
	case "assistant-waits-for-user":
		return UpdateAssistantDtoFirstMessageModeAssistantWaitsForUser, nil
	}
	var t UpdateAssistantDtoFirstMessageMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateAssistantDtoFirstMessageMode) Ptr() *UpdateAssistantDtoFirstMessageMode {
	return &u
}

// These are the options for the assistant's LLM.
type UpdateAssistantDtoModel struct {
	AnyscaleModel     *AnyscaleModel
	AnthropicModel    *AnthropicModel
	CerebrasModel     *CerebrasModel
	CustomLlmModel    *CustomLlmModel
	DeepInfraModel    *DeepInfraModel
	DeepSeekModel     *DeepSeekModel
	GoogleModel       *GoogleModel
	GroqModel         *GroqModel
	InflectionAiModel *InflectionAiModel
	OpenAiModel       *OpenAiModel
	OpenRouterModel   *OpenRouterModel
	PerplexityAiModel *PerplexityAiModel
	TogetherAiModel   *TogetherAiModel
	VapiModel         *VapiModel
	XaiModel          *XaiModel

	typ string
}

func (u *UpdateAssistantDtoModel) GetAnyscaleModel() *AnyscaleModel {
	if u == nil {
		return nil
	}
	return u.AnyscaleModel
}

func (u *UpdateAssistantDtoModel) GetAnthropicModel() *AnthropicModel {
	if u == nil {
		return nil
	}
	return u.AnthropicModel
}

func (u *UpdateAssistantDtoModel) GetCerebrasModel() *CerebrasModel {
	if u == nil {
		return nil
	}
	return u.CerebrasModel
}

func (u *UpdateAssistantDtoModel) GetCustomLlmModel() *CustomLlmModel {
	if u == nil {
		return nil
	}
	return u.CustomLlmModel
}

func (u *UpdateAssistantDtoModel) GetDeepInfraModel() *DeepInfraModel {
	if u == nil {
		return nil
	}
	return u.DeepInfraModel
}

func (u *UpdateAssistantDtoModel) GetDeepSeekModel() *DeepSeekModel {
	if u == nil {
		return nil
	}
	return u.DeepSeekModel
}

func (u *UpdateAssistantDtoModel) GetGoogleModel() *GoogleModel {
	if u == nil {
		return nil
	}
	return u.GoogleModel
}

func (u *UpdateAssistantDtoModel) GetGroqModel() *GroqModel {
	if u == nil {
		return nil
	}
	return u.GroqModel
}

func (u *UpdateAssistantDtoModel) GetInflectionAiModel() *InflectionAiModel {
	if u == nil {
		return nil
	}
	return u.InflectionAiModel
}

func (u *UpdateAssistantDtoModel) GetOpenAiModel() *OpenAiModel {
	if u == nil {
		return nil
	}
	return u.OpenAiModel
}

func (u *UpdateAssistantDtoModel) GetOpenRouterModel() *OpenRouterModel {
	if u == nil {
		return nil
	}
	return u.OpenRouterModel
}

func (u *UpdateAssistantDtoModel) GetPerplexityAiModel() *PerplexityAiModel {
	if u == nil {
		return nil
	}
	return u.PerplexityAiModel
}

func (u *UpdateAssistantDtoModel) GetTogetherAiModel() *TogetherAiModel {
	if u == nil {
		return nil
	}
	return u.TogetherAiModel
}

func (u *UpdateAssistantDtoModel) GetVapiModel() *VapiModel {
	if u == nil {
		return nil
	}
	return u.VapiModel
}

func (u *UpdateAssistantDtoModel) GetXaiModel() *XaiModel {
	if u == nil {
		return nil
	}
	return u.XaiModel
}

func (u *UpdateAssistantDtoModel) UnmarshalJSON(data []byte) error {
	valueAnyscaleModel := new(AnyscaleModel)
	if err := json.Unmarshal(data, &valueAnyscaleModel); err == nil {
		u.typ = "AnyscaleModel"
		u.AnyscaleModel = valueAnyscaleModel
		return nil
	}
	valueAnthropicModel := new(AnthropicModel)
	if err := json.Unmarshal(data, &valueAnthropicModel); err == nil {
		u.typ = "AnthropicModel"
		u.AnthropicModel = valueAnthropicModel
		return nil
	}
	valueCerebrasModel := new(CerebrasModel)
	if err := json.Unmarshal(data, &valueCerebrasModel); err == nil {
		u.typ = "CerebrasModel"
		u.CerebrasModel = valueCerebrasModel
		return nil
	}
	valueCustomLlmModel := new(CustomLlmModel)
	if err := json.Unmarshal(data, &valueCustomLlmModel); err == nil {
		u.typ = "CustomLlmModel"
		u.CustomLlmModel = valueCustomLlmModel
		return nil
	}
	valueDeepInfraModel := new(DeepInfraModel)
	if err := json.Unmarshal(data, &valueDeepInfraModel); err == nil {
		u.typ = "DeepInfraModel"
		u.DeepInfraModel = valueDeepInfraModel
		return nil
	}
	valueDeepSeekModel := new(DeepSeekModel)
	if err := json.Unmarshal(data, &valueDeepSeekModel); err == nil {
		u.typ = "DeepSeekModel"
		u.DeepSeekModel = valueDeepSeekModel
		return nil
	}
	valueGoogleModel := new(GoogleModel)
	if err := json.Unmarshal(data, &valueGoogleModel); err == nil {
		u.typ = "GoogleModel"
		u.GoogleModel = valueGoogleModel
		return nil
	}
	valueGroqModel := new(GroqModel)
	if err := json.Unmarshal(data, &valueGroqModel); err == nil {
		u.typ = "GroqModel"
		u.GroqModel = valueGroqModel
		return nil
	}
	valueInflectionAiModel := new(InflectionAiModel)
	if err := json.Unmarshal(data, &valueInflectionAiModel); err == nil {
		u.typ = "InflectionAiModel"
		u.InflectionAiModel = valueInflectionAiModel
		return nil
	}
	valueOpenAiModel := new(OpenAiModel)
	if err := json.Unmarshal(data, &valueOpenAiModel); err == nil {
		u.typ = "OpenAiModel"
		u.OpenAiModel = valueOpenAiModel
		return nil
	}
	valueOpenRouterModel := new(OpenRouterModel)
	if err := json.Unmarshal(data, &valueOpenRouterModel); err == nil {
		u.typ = "OpenRouterModel"
		u.OpenRouterModel = valueOpenRouterModel
		return nil
	}
	valuePerplexityAiModel := new(PerplexityAiModel)
	if err := json.Unmarshal(data, &valuePerplexityAiModel); err == nil {
		u.typ = "PerplexityAiModel"
		u.PerplexityAiModel = valuePerplexityAiModel
		return nil
	}
	valueTogetherAiModel := new(TogetherAiModel)
	if err := json.Unmarshal(data, &valueTogetherAiModel); err == nil {
		u.typ = "TogetherAiModel"
		u.TogetherAiModel = valueTogetherAiModel
		return nil
	}
	valueVapiModel := new(VapiModel)
	if err := json.Unmarshal(data, &valueVapiModel); err == nil {
		u.typ = "VapiModel"
		u.VapiModel = valueVapiModel
		return nil
	}
	valueXaiModel := new(XaiModel)
	if err := json.Unmarshal(data, &valueXaiModel); err == nil {
		u.typ = "XaiModel"
		u.XaiModel = valueXaiModel
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, u)
}

func (u UpdateAssistantDtoModel) MarshalJSON() ([]byte, error) {
	if u.typ == "AnyscaleModel" || u.AnyscaleModel != nil {
		return json.Marshal(u.AnyscaleModel)
	}
	if u.typ == "AnthropicModel" || u.AnthropicModel != nil {
		return json.Marshal(u.AnthropicModel)
	}
	if u.typ == "CerebrasModel" || u.CerebrasModel != nil {
		return json.Marshal(u.CerebrasModel)
	}
	if u.typ == "CustomLlmModel" || u.CustomLlmModel != nil {
		return json.Marshal(u.CustomLlmModel)
	}
	if u.typ == "DeepInfraModel" || u.DeepInfraModel != nil {
		return json.Marshal(u.DeepInfraModel)
	}
	if u.typ == "DeepSeekModel" || u.DeepSeekModel != nil {
		return json.Marshal(u.DeepSeekModel)
	}
	if u.typ == "GoogleModel" || u.GoogleModel != nil {
		return json.Marshal(u.GoogleModel)
	}
	if u.typ == "GroqModel" || u.GroqModel != nil {
		return json.Marshal(u.GroqModel)
	}
	if u.typ == "InflectionAiModel" || u.InflectionAiModel != nil {
		return json.Marshal(u.InflectionAiModel)
	}
	if u.typ == "OpenAiModel" || u.OpenAiModel != nil {
		return json.Marshal(u.OpenAiModel)
	}
	if u.typ == "OpenRouterModel" || u.OpenRouterModel != nil {
		return json.Marshal(u.OpenRouterModel)
	}
	if u.typ == "PerplexityAiModel" || u.PerplexityAiModel != nil {
		return json.Marshal(u.PerplexityAiModel)
	}
	if u.typ == "TogetherAiModel" || u.TogetherAiModel != nil {
		return json.Marshal(u.TogetherAiModel)
	}
	if u.typ == "VapiModel" || u.VapiModel != nil {
		return json.Marshal(u.VapiModel)
	}
	if u.typ == "XaiModel" || u.XaiModel != nil {
		return json.Marshal(u.XaiModel)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", u)
}

type UpdateAssistantDtoModelVisitor interface {
	VisitAnyscaleModel(*AnyscaleModel) error
	VisitAnthropicModel(*AnthropicModel) error
	VisitCerebrasModel(*CerebrasModel) error
	VisitCustomLlmModel(*CustomLlmModel) error
	VisitDeepInfraModel(*DeepInfraModel) error
	VisitDeepSeekModel(*DeepSeekModel) error
	VisitGoogleModel(*GoogleModel) error
	VisitGroqModel(*GroqModel) error
	VisitInflectionAiModel(*InflectionAiModel) error
	VisitOpenAiModel(*OpenAiModel) error
	VisitOpenRouterModel(*OpenRouterModel) error
	VisitPerplexityAiModel(*PerplexityAiModel) error
	VisitTogetherAiModel(*TogetherAiModel) error
	VisitVapiModel(*VapiModel) error
	VisitXaiModel(*XaiModel) error
}

func (u *UpdateAssistantDtoModel) Accept(visitor UpdateAssistantDtoModelVisitor) error {
	if u.typ == "AnyscaleModel" || u.AnyscaleModel != nil {
		return visitor.VisitAnyscaleModel(u.AnyscaleModel)
	}
	if u.typ == "AnthropicModel" || u.AnthropicModel != nil {
		return visitor.VisitAnthropicModel(u.AnthropicModel)
	}
	if u.typ == "CerebrasModel" || u.CerebrasModel != nil {
		return visitor.VisitCerebrasModel(u.CerebrasModel)
	}
	if u.typ == "CustomLlmModel" || u.CustomLlmModel != nil {
		return visitor.VisitCustomLlmModel(u.CustomLlmModel)
	}
	if u.typ == "DeepInfraModel" || u.DeepInfraModel != nil {
		return visitor.VisitDeepInfraModel(u.DeepInfraModel)
	}
	if u.typ == "DeepSeekModel" || u.DeepSeekModel != nil {
		return visitor.VisitDeepSeekModel(u.DeepSeekModel)
	}
	if u.typ == "GoogleModel" || u.GoogleModel != nil {
		return visitor.VisitGoogleModel(u.GoogleModel)
	}
	if u.typ == "GroqModel" || u.GroqModel != nil {
		return visitor.VisitGroqModel(u.GroqModel)
	}
	if u.typ == "InflectionAiModel" || u.InflectionAiModel != nil {
		return visitor.VisitInflectionAiModel(u.InflectionAiModel)
	}
	if u.typ == "OpenAiModel" || u.OpenAiModel != nil {
		return visitor.VisitOpenAiModel(u.OpenAiModel)
	}
	if u.typ == "OpenRouterModel" || u.OpenRouterModel != nil {
		return visitor.VisitOpenRouterModel(u.OpenRouterModel)
	}
	if u.typ == "PerplexityAiModel" || u.PerplexityAiModel != nil {
		return visitor.VisitPerplexityAiModel(u.PerplexityAiModel)
	}
	if u.typ == "TogetherAiModel" || u.TogetherAiModel != nil {
		return visitor.VisitTogetherAiModel(u.TogetherAiModel)
	}
	if u.typ == "VapiModel" || u.VapiModel != nil {
		return visitor.VisitVapiModel(u.VapiModel)
	}
	if u.typ == "XaiModel" || u.XaiModel != nil {
		return visitor.VisitXaiModel(u.XaiModel)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", u)
}

type UpdateAssistantDtoServerMessagesItem string

const (
	UpdateAssistantDtoServerMessagesItemConversationUpdate            UpdateAssistantDtoServerMessagesItem = "conversation-update"
	UpdateAssistantDtoServerMessagesItemEndOfCallReport               UpdateAssistantDtoServerMessagesItem = "end-of-call-report"
	UpdateAssistantDtoServerMessagesItemFunctionCall                  UpdateAssistantDtoServerMessagesItem = "function-call"
	UpdateAssistantDtoServerMessagesItemHang                          UpdateAssistantDtoServerMessagesItem = "hang"
	UpdateAssistantDtoServerMessagesItemLanguageChanged               UpdateAssistantDtoServerMessagesItem = "language-changed"
	UpdateAssistantDtoServerMessagesItemLanguageChangeDetected        UpdateAssistantDtoServerMessagesItem = "language-change-detected"
	UpdateAssistantDtoServerMessagesItemModelOutput                   UpdateAssistantDtoServerMessagesItem = "model-output"
	UpdateAssistantDtoServerMessagesItemPhoneCallControl              UpdateAssistantDtoServerMessagesItem = "phone-call-control"
	UpdateAssistantDtoServerMessagesItemSpeechUpdate                  UpdateAssistantDtoServerMessagesItem = "speech-update"
	UpdateAssistantDtoServerMessagesItemStatusUpdate                  UpdateAssistantDtoServerMessagesItem = "status-update"
	UpdateAssistantDtoServerMessagesItemTranscript                    UpdateAssistantDtoServerMessagesItem = "transcript"
	UpdateAssistantDtoServerMessagesItemTranscriptTranscriptTypeFinal UpdateAssistantDtoServerMessagesItem = "transcript[transcriptType='final']"
	UpdateAssistantDtoServerMessagesItemToolCalls                     UpdateAssistantDtoServerMessagesItem = "tool-calls"
	UpdateAssistantDtoServerMessagesItemTransferDestinationRequest    UpdateAssistantDtoServerMessagesItem = "transfer-destination-request"
	UpdateAssistantDtoServerMessagesItemTransferUpdate                UpdateAssistantDtoServerMessagesItem = "transfer-update"
	UpdateAssistantDtoServerMessagesItemUserInterrupted               UpdateAssistantDtoServerMessagesItem = "user-interrupted"
	UpdateAssistantDtoServerMessagesItemVoiceInput                    UpdateAssistantDtoServerMessagesItem = "voice-input"
)

func NewUpdateAssistantDtoServerMessagesItemFromString(s string) (UpdateAssistantDtoServerMessagesItem, error) {
	switch s {
	case "conversation-update":
		return UpdateAssistantDtoServerMessagesItemConversationUpdate, nil
	case "end-of-call-report":
		return UpdateAssistantDtoServerMessagesItemEndOfCallReport, nil
	case "function-call":
		return UpdateAssistantDtoServerMessagesItemFunctionCall, nil
	case "hang":
		return UpdateAssistantDtoServerMessagesItemHang, nil
	case "language-changed":
		return UpdateAssistantDtoServerMessagesItemLanguageChanged, nil
	case "language-change-detected":
		return UpdateAssistantDtoServerMessagesItemLanguageChangeDetected, nil
	case "model-output":
		return UpdateAssistantDtoServerMessagesItemModelOutput, nil
	case "phone-call-control":
		return UpdateAssistantDtoServerMessagesItemPhoneCallControl, nil
	case "speech-update":
		return UpdateAssistantDtoServerMessagesItemSpeechUpdate, nil
	case "status-update":
		return UpdateAssistantDtoServerMessagesItemStatusUpdate, nil
	case "transcript":
		return UpdateAssistantDtoServerMessagesItemTranscript, nil
	case "transcript[transcriptType='final']":
		return UpdateAssistantDtoServerMessagesItemTranscriptTranscriptTypeFinal, nil
	case "tool-calls":
		return UpdateAssistantDtoServerMessagesItemToolCalls, nil
	case "transfer-destination-request":
		return UpdateAssistantDtoServerMessagesItemTransferDestinationRequest, nil
	case "transfer-update":
		return UpdateAssistantDtoServerMessagesItemTransferUpdate, nil
	case "user-interrupted":
		return UpdateAssistantDtoServerMessagesItemUserInterrupted, nil
	case "voice-input":
		return UpdateAssistantDtoServerMessagesItemVoiceInput, nil
	}
	var t UpdateAssistantDtoServerMessagesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateAssistantDtoServerMessagesItem) Ptr() *UpdateAssistantDtoServerMessagesItem {
	return &u
}

// These are the options for the assistant's transcriber.
type UpdateAssistantDtoTranscriber struct {
	AssemblyAiTranscriber   *AssemblyAiTranscriber
	AzureSpeechTranscriber  *AzureSpeechTranscriber
	CustomTranscriber       *CustomTranscriber
	DeepgramTranscriber     *DeepgramTranscriber
	ElevenLabsTranscriber   *ElevenLabsTranscriber
	GladiaTranscriber       *GladiaTranscriber
	SpeechmaticsTranscriber *SpeechmaticsTranscriber
	TalkscriberTranscriber  *TalkscriberTranscriber
	GoogleTranscriber       *GoogleTranscriber
	OpenAiTranscriber       *OpenAiTranscriber

	typ string
}

func (u *UpdateAssistantDtoTranscriber) GetAssemblyAiTranscriber() *AssemblyAiTranscriber {
	if u == nil {
		return nil
	}
	return u.AssemblyAiTranscriber
}

func (u *UpdateAssistantDtoTranscriber) GetAzureSpeechTranscriber() *AzureSpeechTranscriber {
	if u == nil {
		return nil
	}
	return u.AzureSpeechTranscriber
}

func (u *UpdateAssistantDtoTranscriber) GetCustomTranscriber() *CustomTranscriber {
	if u == nil {
		return nil
	}
	return u.CustomTranscriber
}

func (u *UpdateAssistantDtoTranscriber) GetDeepgramTranscriber() *DeepgramTranscriber {
	if u == nil {
		return nil
	}
	return u.DeepgramTranscriber
}

func (u *UpdateAssistantDtoTranscriber) GetElevenLabsTranscriber() *ElevenLabsTranscriber {
	if u == nil {
		return nil
	}
	return u.ElevenLabsTranscriber
}

func (u *UpdateAssistantDtoTranscriber) GetGladiaTranscriber() *GladiaTranscriber {
	if u == nil {
		return nil
	}
	return u.GladiaTranscriber
}

func (u *UpdateAssistantDtoTranscriber) GetSpeechmaticsTranscriber() *SpeechmaticsTranscriber {
	if u == nil {
		return nil
	}
	return u.SpeechmaticsTranscriber
}

func (u *UpdateAssistantDtoTranscriber) GetTalkscriberTranscriber() *TalkscriberTranscriber {
	if u == nil {
		return nil
	}
	return u.TalkscriberTranscriber
}

func (u *UpdateAssistantDtoTranscriber) GetGoogleTranscriber() *GoogleTranscriber {
	if u == nil {
		return nil
	}
	return u.GoogleTranscriber
}

func (u *UpdateAssistantDtoTranscriber) GetOpenAiTranscriber() *OpenAiTranscriber {
	if u == nil {
		return nil
	}
	return u.OpenAiTranscriber
}

func (u *UpdateAssistantDtoTranscriber) UnmarshalJSON(data []byte) error {
	valueAssemblyAiTranscriber := new(AssemblyAiTranscriber)
	if err := json.Unmarshal(data, &valueAssemblyAiTranscriber); err == nil {
		u.typ = "AssemblyAiTranscriber"
		u.AssemblyAiTranscriber = valueAssemblyAiTranscriber
		return nil
	}
	valueAzureSpeechTranscriber := new(AzureSpeechTranscriber)
	if err := json.Unmarshal(data, &valueAzureSpeechTranscriber); err == nil {
		u.typ = "AzureSpeechTranscriber"
		u.AzureSpeechTranscriber = valueAzureSpeechTranscriber
		return nil
	}
	valueCustomTranscriber := new(CustomTranscriber)
	if err := json.Unmarshal(data, &valueCustomTranscriber); err == nil {
		u.typ = "CustomTranscriber"
		u.CustomTranscriber = valueCustomTranscriber
		return nil
	}
	valueDeepgramTranscriber := new(DeepgramTranscriber)
	if err := json.Unmarshal(data, &valueDeepgramTranscriber); err == nil {
		u.typ = "DeepgramTranscriber"
		u.DeepgramTranscriber = valueDeepgramTranscriber
		return nil
	}
	valueElevenLabsTranscriber := new(ElevenLabsTranscriber)
	if err := json.Unmarshal(data, &valueElevenLabsTranscriber); err == nil {
		u.typ = "ElevenLabsTranscriber"
		u.ElevenLabsTranscriber = valueElevenLabsTranscriber
		return nil
	}
	valueGladiaTranscriber := new(GladiaTranscriber)
	if err := json.Unmarshal(data, &valueGladiaTranscriber); err == nil {
		u.typ = "GladiaTranscriber"
		u.GladiaTranscriber = valueGladiaTranscriber
		return nil
	}
	valueSpeechmaticsTranscriber := new(SpeechmaticsTranscriber)
	if err := json.Unmarshal(data, &valueSpeechmaticsTranscriber); err == nil {
		u.typ = "SpeechmaticsTranscriber"
		u.SpeechmaticsTranscriber = valueSpeechmaticsTranscriber
		return nil
	}
	valueTalkscriberTranscriber := new(TalkscriberTranscriber)
	if err := json.Unmarshal(data, &valueTalkscriberTranscriber); err == nil {
		u.typ = "TalkscriberTranscriber"
		u.TalkscriberTranscriber = valueTalkscriberTranscriber
		return nil
	}
	valueGoogleTranscriber := new(GoogleTranscriber)
	if err := json.Unmarshal(data, &valueGoogleTranscriber); err == nil {
		u.typ = "GoogleTranscriber"
		u.GoogleTranscriber = valueGoogleTranscriber
		return nil
	}
	valueOpenAiTranscriber := new(OpenAiTranscriber)
	if err := json.Unmarshal(data, &valueOpenAiTranscriber); err == nil {
		u.typ = "OpenAiTranscriber"
		u.OpenAiTranscriber = valueOpenAiTranscriber
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, u)
}

func (u UpdateAssistantDtoTranscriber) MarshalJSON() ([]byte, error) {
	if u.typ == "AssemblyAiTranscriber" || u.AssemblyAiTranscriber != nil {
		return json.Marshal(u.AssemblyAiTranscriber)
	}
	if u.typ == "AzureSpeechTranscriber" || u.AzureSpeechTranscriber != nil {
		return json.Marshal(u.AzureSpeechTranscriber)
	}
	if u.typ == "CustomTranscriber" || u.CustomTranscriber != nil {
		return json.Marshal(u.CustomTranscriber)
	}
	if u.typ == "DeepgramTranscriber" || u.DeepgramTranscriber != nil {
		return json.Marshal(u.DeepgramTranscriber)
	}
	if u.typ == "ElevenLabsTranscriber" || u.ElevenLabsTranscriber != nil {
		return json.Marshal(u.ElevenLabsTranscriber)
	}
	if u.typ == "GladiaTranscriber" || u.GladiaTranscriber != nil {
		return json.Marshal(u.GladiaTranscriber)
	}
	if u.typ == "SpeechmaticsTranscriber" || u.SpeechmaticsTranscriber != nil {
		return json.Marshal(u.SpeechmaticsTranscriber)
	}
	if u.typ == "TalkscriberTranscriber" || u.TalkscriberTranscriber != nil {
		return json.Marshal(u.TalkscriberTranscriber)
	}
	if u.typ == "GoogleTranscriber" || u.GoogleTranscriber != nil {
		return json.Marshal(u.GoogleTranscriber)
	}
	if u.typ == "OpenAiTranscriber" || u.OpenAiTranscriber != nil {
		return json.Marshal(u.OpenAiTranscriber)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", u)
}

type UpdateAssistantDtoTranscriberVisitor interface {
	VisitAssemblyAiTranscriber(*AssemblyAiTranscriber) error
	VisitAzureSpeechTranscriber(*AzureSpeechTranscriber) error
	VisitCustomTranscriber(*CustomTranscriber) error
	VisitDeepgramTranscriber(*DeepgramTranscriber) error
	VisitElevenLabsTranscriber(*ElevenLabsTranscriber) error
	VisitGladiaTranscriber(*GladiaTranscriber) error
	VisitSpeechmaticsTranscriber(*SpeechmaticsTranscriber) error
	VisitTalkscriberTranscriber(*TalkscriberTranscriber) error
	VisitGoogleTranscriber(*GoogleTranscriber) error
	VisitOpenAiTranscriber(*OpenAiTranscriber) error
}

func (u *UpdateAssistantDtoTranscriber) Accept(visitor UpdateAssistantDtoTranscriberVisitor) error {
	if u.typ == "AssemblyAiTranscriber" || u.AssemblyAiTranscriber != nil {
		return visitor.VisitAssemblyAiTranscriber(u.AssemblyAiTranscriber)
	}
	if u.typ == "AzureSpeechTranscriber" || u.AzureSpeechTranscriber != nil {
		return visitor.VisitAzureSpeechTranscriber(u.AzureSpeechTranscriber)
	}
	if u.typ == "CustomTranscriber" || u.CustomTranscriber != nil {
		return visitor.VisitCustomTranscriber(u.CustomTranscriber)
	}
	if u.typ == "DeepgramTranscriber" || u.DeepgramTranscriber != nil {
		return visitor.VisitDeepgramTranscriber(u.DeepgramTranscriber)
	}
	if u.typ == "ElevenLabsTranscriber" || u.ElevenLabsTranscriber != nil {
		return visitor.VisitElevenLabsTranscriber(u.ElevenLabsTranscriber)
	}
	if u.typ == "GladiaTranscriber" || u.GladiaTranscriber != nil {
		return visitor.VisitGladiaTranscriber(u.GladiaTranscriber)
	}
	if u.typ == "SpeechmaticsTranscriber" || u.SpeechmaticsTranscriber != nil {
		return visitor.VisitSpeechmaticsTranscriber(u.SpeechmaticsTranscriber)
	}
	if u.typ == "TalkscriberTranscriber" || u.TalkscriberTranscriber != nil {
		return visitor.VisitTalkscriberTranscriber(u.TalkscriberTranscriber)
	}
	if u.typ == "GoogleTranscriber" || u.GoogleTranscriber != nil {
		return visitor.VisitGoogleTranscriber(u.GoogleTranscriber)
	}
	if u.typ == "OpenAiTranscriber" || u.OpenAiTranscriber != nil {
		return visitor.VisitOpenAiTranscriber(u.OpenAiTranscriber)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", u)
}

// These are the options for the assistant's voice.
type UpdateAssistantDtoVoice struct {
	AzureVoice      *AzureVoice
	CartesiaVoice   *CartesiaVoice
	CustomVoice     *CustomVoice
	DeepgramVoice   *DeepgramVoice
	ElevenLabsVoice *ElevenLabsVoice
	HumeVoice       *HumeVoice
	LmntVoice       *LmntVoice
	NeuphonicVoice  *NeuphonicVoice
	OpenAiVoice     *OpenAiVoice
	PlayHtVoice     *PlayHtVoice
	RimeAiVoice     *RimeAiVoice
	SmallestAiVoice *SmallestAiVoice
	TavusVoice      *TavusVoice
	VapiVoice       *VapiVoice

	typ string
}

func (u *UpdateAssistantDtoVoice) GetAzureVoice() *AzureVoice {
	if u == nil {
		return nil
	}
	return u.AzureVoice
}

func (u *UpdateAssistantDtoVoice) GetCartesiaVoice() *CartesiaVoice {
	if u == nil {
		return nil
	}
	return u.CartesiaVoice
}

func (u *UpdateAssistantDtoVoice) GetCustomVoice() *CustomVoice {
	if u == nil {
		return nil
	}
	return u.CustomVoice
}

func (u *UpdateAssistantDtoVoice) GetDeepgramVoice() *DeepgramVoice {
	if u == nil {
		return nil
	}
	return u.DeepgramVoice
}

func (u *UpdateAssistantDtoVoice) GetElevenLabsVoice() *ElevenLabsVoice {
	if u == nil {
		return nil
	}
	return u.ElevenLabsVoice
}

func (u *UpdateAssistantDtoVoice) GetHumeVoice() *HumeVoice {
	if u == nil {
		return nil
	}
	return u.HumeVoice
}

func (u *UpdateAssistantDtoVoice) GetLmntVoice() *LmntVoice {
	if u == nil {
		return nil
	}
	return u.LmntVoice
}

func (u *UpdateAssistantDtoVoice) GetNeuphonicVoice() *NeuphonicVoice {
	if u == nil {
		return nil
	}
	return u.NeuphonicVoice
}

func (u *UpdateAssistantDtoVoice) GetOpenAiVoice() *OpenAiVoice {
	if u == nil {
		return nil
	}
	return u.OpenAiVoice
}

func (u *UpdateAssistantDtoVoice) GetPlayHtVoice() *PlayHtVoice {
	if u == nil {
		return nil
	}
	return u.PlayHtVoice
}

func (u *UpdateAssistantDtoVoice) GetRimeAiVoice() *RimeAiVoice {
	if u == nil {
		return nil
	}
	return u.RimeAiVoice
}

func (u *UpdateAssistantDtoVoice) GetSmallestAiVoice() *SmallestAiVoice {
	if u == nil {
		return nil
	}
	return u.SmallestAiVoice
}

func (u *UpdateAssistantDtoVoice) GetTavusVoice() *TavusVoice {
	if u == nil {
		return nil
	}
	return u.TavusVoice
}

func (u *UpdateAssistantDtoVoice) GetVapiVoice() *VapiVoice {
	if u == nil {
		return nil
	}
	return u.VapiVoice
}

func (u *UpdateAssistantDtoVoice) UnmarshalJSON(data []byte) error {
	valueAzureVoice := new(AzureVoice)
	if err := json.Unmarshal(data, &valueAzureVoice); err == nil {
		u.typ = "AzureVoice"
		u.AzureVoice = valueAzureVoice
		return nil
	}
	valueCartesiaVoice := new(CartesiaVoice)
	if err := json.Unmarshal(data, &valueCartesiaVoice); err == nil {
		u.typ = "CartesiaVoice"
		u.CartesiaVoice = valueCartesiaVoice
		return nil
	}
	valueCustomVoice := new(CustomVoice)
	if err := json.Unmarshal(data, &valueCustomVoice); err == nil {
		u.typ = "CustomVoice"
		u.CustomVoice = valueCustomVoice
		return nil
	}
	valueDeepgramVoice := new(DeepgramVoice)
	if err := json.Unmarshal(data, &valueDeepgramVoice); err == nil {
		u.typ = "DeepgramVoice"
		u.DeepgramVoice = valueDeepgramVoice
		return nil
	}
	valueElevenLabsVoice := new(ElevenLabsVoice)
	if err := json.Unmarshal(data, &valueElevenLabsVoice); err == nil {
		u.typ = "ElevenLabsVoice"
		u.ElevenLabsVoice = valueElevenLabsVoice
		return nil
	}
	valueHumeVoice := new(HumeVoice)
	if err := json.Unmarshal(data, &valueHumeVoice); err == nil {
		u.typ = "HumeVoice"
		u.HumeVoice = valueHumeVoice
		return nil
	}
	valueLmntVoice := new(LmntVoice)
	if err := json.Unmarshal(data, &valueLmntVoice); err == nil {
		u.typ = "LmntVoice"
		u.LmntVoice = valueLmntVoice
		return nil
	}
	valueNeuphonicVoice := new(NeuphonicVoice)
	if err := json.Unmarshal(data, &valueNeuphonicVoice); err == nil {
		u.typ = "NeuphonicVoice"
		u.NeuphonicVoice = valueNeuphonicVoice
		return nil
	}
	valueOpenAiVoice := new(OpenAiVoice)
	if err := json.Unmarshal(data, &valueOpenAiVoice); err == nil {
		u.typ = "OpenAiVoice"
		u.OpenAiVoice = valueOpenAiVoice
		return nil
	}
	valuePlayHtVoice := new(PlayHtVoice)
	if err := json.Unmarshal(data, &valuePlayHtVoice); err == nil {
		u.typ = "PlayHtVoice"
		u.PlayHtVoice = valuePlayHtVoice
		return nil
	}
	valueRimeAiVoice := new(RimeAiVoice)
	if err := json.Unmarshal(data, &valueRimeAiVoice); err == nil {
		u.typ = "RimeAiVoice"
		u.RimeAiVoice = valueRimeAiVoice
		return nil
	}
	valueSmallestAiVoice := new(SmallestAiVoice)
	if err := json.Unmarshal(data, &valueSmallestAiVoice); err == nil {
		u.typ = "SmallestAiVoice"
		u.SmallestAiVoice = valueSmallestAiVoice
		return nil
	}
	valueTavusVoice := new(TavusVoice)
	if err := json.Unmarshal(data, &valueTavusVoice); err == nil {
		u.typ = "TavusVoice"
		u.TavusVoice = valueTavusVoice
		return nil
	}
	valueVapiVoice := new(VapiVoice)
	if err := json.Unmarshal(data, &valueVapiVoice); err == nil {
		u.typ = "VapiVoice"
		u.VapiVoice = valueVapiVoice
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, u)
}

func (u UpdateAssistantDtoVoice) MarshalJSON() ([]byte, error) {
	if u.typ == "AzureVoice" || u.AzureVoice != nil {
		return json.Marshal(u.AzureVoice)
	}
	if u.typ == "CartesiaVoice" || u.CartesiaVoice != nil {
		return json.Marshal(u.CartesiaVoice)
	}
	if u.typ == "CustomVoice" || u.CustomVoice != nil {
		return json.Marshal(u.CustomVoice)
	}
	if u.typ == "DeepgramVoice" || u.DeepgramVoice != nil {
		return json.Marshal(u.DeepgramVoice)
	}
	if u.typ == "ElevenLabsVoice" || u.ElevenLabsVoice != nil {
		return json.Marshal(u.ElevenLabsVoice)
	}
	if u.typ == "HumeVoice" || u.HumeVoice != nil {
		return json.Marshal(u.HumeVoice)
	}
	if u.typ == "LmntVoice" || u.LmntVoice != nil {
		return json.Marshal(u.LmntVoice)
	}
	if u.typ == "NeuphonicVoice" || u.NeuphonicVoice != nil {
		return json.Marshal(u.NeuphonicVoice)
	}
	if u.typ == "OpenAiVoice" || u.OpenAiVoice != nil {
		return json.Marshal(u.OpenAiVoice)
	}
	if u.typ == "PlayHtVoice" || u.PlayHtVoice != nil {
		return json.Marshal(u.PlayHtVoice)
	}
	if u.typ == "RimeAiVoice" || u.RimeAiVoice != nil {
		return json.Marshal(u.RimeAiVoice)
	}
	if u.typ == "SmallestAiVoice" || u.SmallestAiVoice != nil {
		return json.Marshal(u.SmallestAiVoice)
	}
	if u.typ == "TavusVoice" || u.TavusVoice != nil {
		return json.Marshal(u.TavusVoice)
	}
	if u.typ == "VapiVoice" || u.VapiVoice != nil {
		return json.Marshal(u.VapiVoice)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", u)
}

type UpdateAssistantDtoVoiceVisitor interface {
	VisitAzureVoice(*AzureVoice) error
	VisitCartesiaVoice(*CartesiaVoice) error
	VisitCustomVoice(*CustomVoice) error
	VisitDeepgramVoice(*DeepgramVoice) error
	VisitElevenLabsVoice(*ElevenLabsVoice) error
	VisitHumeVoice(*HumeVoice) error
	VisitLmntVoice(*LmntVoice) error
	VisitNeuphonicVoice(*NeuphonicVoice) error
	VisitOpenAiVoice(*OpenAiVoice) error
	VisitPlayHtVoice(*PlayHtVoice) error
	VisitRimeAiVoice(*RimeAiVoice) error
	VisitSmallestAiVoice(*SmallestAiVoice) error
	VisitTavusVoice(*TavusVoice) error
	VisitVapiVoice(*VapiVoice) error
}

func (u *UpdateAssistantDtoVoice) Accept(visitor UpdateAssistantDtoVoiceVisitor) error {
	if u.typ == "AzureVoice" || u.AzureVoice != nil {
		return visitor.VisitAzureVoice(u.AzureVoice)
	}
	if u.typ == "CartesiaVoice" || u.CartesiaVoice != nil {
		return visitor.VisitCartesiaVoice(u.CartesiaVoice)
	}
	if u.typ == "CustomVoice" || u.CustomVoice != nil {
		return visitor.VisitCustomVoice(u.CustomVoice)
	}
	if u.typ == "DeepgramVoice" || u.DeepgramVoice != nil {
		return visitor.VisitDeepgramVoice(u.DeepgramVoice)
	}
	if u.typ == "ElevenLabsVoice" || u.ElevenLabsVoice != nil {
		return visitor.VisitElevenLabsVoice(u.ElevenLabsVoice)
	}
	if u.typ == "HumeVoice" || u.HumeVoice != nil {
		return visitor.VisitHumeVoice(u.HumeVoice)
	}
	if u.typ == "LmntVoice" || u.LmntVoice != nil {
		return visitor.VisitLmntVoice(u.LmntVoice)
	}
	if u.typ == "NeuphonicVoice" || u.NeuphonicVoice != nil {
		return visitor.VisitNeuphonicVoice(u.NeuphonicVoice)
	}
	if u.typ == "OpenAiVoice" || u.OpenAiVoice != nil {
		return visitor.VisitOpenAiVoice(u.OpenAiVoice)
	}
	if u.typ == "PlayHtVoice" || u.PlayHtVoice != nil {
		return visitor.VisitPlayHtVoice(u.PlayHtVoice)
	}
	if u.typ == "RimeAiVoice" || u.RimeAiVoice != nil {
		return visitor.VisitRimeAiVoice(u.RimeAiVoice)
	}
	if u.typ == "SmallestAiVoice" || u.SmallestAiVoice != nil {
		return visitor.VisitSmallestAiVoice(u.SmallestAiVoice)
	}
	if u.typ == "TavusVoice" || u.TavusVoice != nil {
		return visitor.VisitTavusVoice(u.TavusVoice)
	}
	if u.typ == "VapiVoice" || u.VapiVoice != nil {
		return visitor.VisitVapiVoice(u.VapiVoice)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", u)
}

// These are the settings to configure or disable voicemail detection. Alternatively, voicemail detection can be configured using the model.tools=[VoicemailTool].
// This uses Twilio's built-in detection while the VoicemailTool relies on the model to detect if a voicemail was reached.
// You can use neither of them, one of them, or both of them. By default, Twilio built-in detection is enabled while VoicemailTool is not.
type UpdateAssistantDtoVoicemailDetection struct {
	GoogleVoicemailDetectionPlan *GoogleVoicemailDetectionPlan
	OpenAiVoicemailDetectionPlan *OpenAiVoicemailDetectionPlan
	TwilioVoicemailDetectionPlan *TwilioVoicemailDetectionPlan
	VapiVoicemailDetectionPlan   *VapiVoicemailDetectionPlan

	typ string
}

func (u *UpdateAssistantDtoVoicemailDetection) GetGoogleVoicemailDetectionPlan() *GoogleVoicemailDetectionPlan {
	if u == nil {
		return nil
	}
	return u.GoogleVoicemailDetectionPlan
}

func (u *UpdateAssistantDtoVoicemailDetection) GetOpenAiVoicemailDetectionPlan() *OpenAiVoicemailDetectionPlan {
	if u == nil {
		return nil
	}
	return u.OpenAiVoicemailDetectionPlan
}

func (u *UpdateAssistantDtoVoicemailDetection) GetTwilioVoicemailDetectionPlan() *TwilioVoicemailDetectionPlan {
	if u == nil {
		return nil
	}
	return u.TwilioVoicemailDetectionPlan
}

func (u *UpdateAssistantDtoVoicemailDetection) GetVapiVoicemailDetectionPlan() *VapiVoicemailDetectionPlan {
	if u == nil {
		return nil
	}
	return u.VapiVoicemailDetectionPlan
}

func (u *UpdateAssistantDtoVoicemailDetection) UnmarshalJSON(data []byte) error {
	valueGoogleVoicemailDetectionPlan := new(GoogleVoicemailDetectionPlan)
	if err := json.Unmarshal(data, &valueGoogleVoicemailDetectionPlan); err == nil {
		u.typ = "GoogleVoicemailDetectionPlan"
		u.GoogleVoicemailDetectionPlan = valueGoogleVoicemailDetectionPlan
		return nil
	}
	valueOpenAiVoicemailDetectionPlan := new(OpenAiVoicemailDetectionPlan)
	if err := json.Unmarshal(data, &valueOpenAiVoicemailDetectionPlan); err == nil {
		u.typ = "OpenAiVoicemailDetectionPlan"
		u.OpenAiVoicemailDetectionPlan = valueOpenAiVoicemailDetectionPlan
		return nil
	}
	valueTwilioVoicemailDetectionPlan := new(TwilioVoicemailDetectionPlan)
	if err := json.Unmarshal(data, &valueTwilioVoicemailDetectionPlan); err == nil {
		u.typ = "TwilioVoicemailDetectionPlan"
		u.TwilioVoicemailDetectionPlan = valueTwilioVoicemailDetectionPlan
		return nil
	}
	valueVapiVoicemailDetectionPlan := new(VapiVoicemailDetectionPlan)
	if err := json.Unmarshal(data, &valueVapiVoicemailDetectionPlan); err == nil {
		u.typ = "VapiVoicemailDetectionPlan"
		u.VapiVoicemailDetectionPlan = valueVapiVoicemailDetectionPlan
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, u)
}

func (u UpdateAssistantDtoVoicemailDetection) MarshalJSON() ([]byte, error) {
	if u.typ == "GoogleVoicemailDetectionPlan" || u.GoogleVoicemailDetectionPlan != nil {
		return json.Marshal(u.GoogleVoicemailDetectionPlan)
	}
	if u.typ == "OpenAiVoicemailDetectionPlan" || u.OpenAiVoicemailDetectionPlan != nil {
		return json.Marshal(u.OpenAiVoicemailDetectionPlan)
	}
	if u.typ == "TwilioVoicemailDetectionPlan" || u.TwilioVoicemailDetectionPlan != nil {
		return json.Marshal(u.TwilioVoicemailDetectionPlan)
	}
	if u.typ == "VapiVoicemailDetectionPlan" || u.VapiVoicemailDetectionPlan != nil {
		return json.Marshal(u.VapiVoicemailDetectionPlan)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", u)
}

type UpdateAssistantDtoVoicemailDetectionVisitor interface {
	VisitGoogleVoicemailDetectionPlan(*GoogleVoicemailDetectionPlan) error
	VisitOpenAiVoicemailDetectionPlan(*OpenAiVoicemailDetectionPlan) error
	VisitTwilioVoicemailDetectionPlan(*TwilioVoicemailDetectionPlan) error
	VisitVapiVoicemailDetectionPlan(*VapiVoicemailDetectionPlan) error
}

func (u *UpdateAssistantDtoVoicemailDetection) Accept(visitor UpdateAssistantDtoVoicemailDetectionVisitor) error {
	if u.typ == "GoogleVoicemailDetectionPlan" || u.GoogleVoicemailDetectionPlan != nil {
		return visitor.VisitGoogleVoicemailDetectionPlan(u.GoogleVoicemailDetectionPlan)
	}
	if u.typ == "OpenAiVoicemailDetectionPlan" || u.OpenAiVoicemailDetectionPlan != nil {
		return visitor.VisitOpenAiVoicemailDetectionPlan(u.OpenAiVoicemailDetectionPlan)
	}
	if u.typ == "TwilioVoicemailDetectionPlan" || u.TwilioVoicemailDetectionPlan != nil {
		return visitor.VisitTwilioVoicemailDetectionPlan(u.TwilioVoicemailDetectionPlan)
	}
	if u.typ == "VapiVoicemailDetectionPlan" || u.VapiVoicemailDetectionPlan != nil {
		return visitor.VisitVapiVoicemailDetectionPlan(u.VapiVoicemailDetectionPlan)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", u)
}

type UpdateAssistantDto struct {
	// These are the options for the assistant's transcriber.
	Transcriber *UpdateAssistantDtoTranscriber `json:"transcriber,omitempty" url:"-"`
	// These are the options for the assistant's LLM.
	Model *UpdateAssistantDtoModel `json:"model,omitempty" url:"-"`
	// These are the options for the assistant's voice.
	Voice *UpdateAssistantDtoVoice `json:"voice,omitempty" url:"-"`
	// This is the first message that the assistant will say. This can also be a URL to a containerized audio file (mp3, wav, etc.).
	//
	// If unspecified, assistant will wait for user to speak and use the model to respond once they speak.
	FirstMessage                     *string `json:"firstMessage,omitempty" url:"-"`
	FirstMessageInterruptionsEnabled *bool   `json:"firstMessageInterruptionsEnabled,omitempty" url:"-"`
	// This is the mode for the first message. Default is 'assistant-speaks-first'.
	//
	// Use:
	// - 'assistant-speaks-first' to have the assistant speak first.
	// - 'assistant-waits-for-user' to have the assistant wait for the user to speak first.
	// - 'assistant-speaks-first-with-model-generated-message' to have the assistant speak first with a message generated by the model based on the conversation state. (`assistant.model.messages` at call start, `call.messages` at squad transfer points).
	//
	// @default 'assistant-speaks-first'
	FirstMessageMode *UpdateAssistantDtoFirstMessageMode `json:"firstMessageMode,omitempty" url:"-"`
	// These are the settings to configure or disable voicemail detection. Alternatively, voicemail detection can be configured using the model.tools=[VoicemailTool].
	// This uses Twilio's built-in detection while the VoicemailTool relies on the model to detect if a voicemail was reached.
	// You can use neither of them, one of them, or both of them. By default, Twilio built-in detection is enabled while VoicemailTool is not.
	VoicemailDetection *UpdateAssistantDtoVoicemailDetection `json:"voicemailDetection,omitempty" url:"-"`
	// These are the messages that will be sent to your Client SDKs. Default is conversation-update,function-call,hang,model-output,speech-update,status-update,transfer-update,transcript,tool-calls,user-interrupted,voice-input,workflow.node.started. You can check the shape of the messages in ClientMessage schema.
	ClientMessages []UpdateAssistantDtoClientMessagesItem `json:"clientMessages,omitempty" url:"-"`
	// These are the messages that will be sent to your Server URL. Default is conversation-update,end-of-call-report,function-call,hang,speech-update,status-update,tool-calls,transfer-destination-request,user-interrupted. You can check the shape of the messages in ServerMessage schema.
	ServerMessages []UpdateAssistantDtoServerMessagesItem `json:"serverMessages,omitempty" url:"-"`
	// How many seconds of silence to wait before ending the call. Defaults to 30.
	//
	// @default 30
	SilenceTimeoutSeconds *float64 `json:"silenceTimeoutSeconds,omitempty" url:"-"`
	// This is the maximum number of seconds that the call will last. When the call reaches this duration, it will be ended.
	//
	// @default 600 (10 minutes)
	MaxDurationSeconds *float64 `json:"maxDurationSeconds,omitempty" url:"-"`
	// This is the background sound in the call. Default for phone calls is 'office' and default for web calls is 'off'.
	// You can also provide a custom sound by providing a URL to an audio file.
	BackgroundSound *UpdateAssistantDtoBackgroundSound `json:"backgroundSound,omitempty" url:"-"`
	// This enables filtering of noise and background speech while the user is talking.
	//
	// Default `false` while in beta.
	//
	// @default false
	BackgroundDenoisingEnabled *bool `json:"backgroundDenoisingEnabled,omitempty" url:"-"`
	// This determines whether the model's output is used in conversation history rather than the transcription of assistant's speech.
	//
	// Default `false` while in beta.
	//
	// @default false
	ModelOutputInMessagesEnabled *bool `json:"modelOutputInMessagesEnabled,omitempty" url:"-"`
	// These are the configurations to be passed to the transport providers of assistant's calls, like Twilio. You can store multiple configurations for different transport providers. For a call, only the configuration matching the call transport provider is used.
	TransportConfigurations []*TransportConfigurationTwilio `json:"transportConfigurations,omitempty" url:"-"`
	// This is the plan for observability configuration of assistant's calls.
	// Currently supports Langfuse for tracing and monitoring.
	ObservabilityPlan *LangfuseObservabilityPlan `json:"observabilityPlan,omitempty" url:"-"`
	// These are dynamic credentials that will be used for the assistant calls. By default, all the credentials are available for use in the call but you can supplement an additional credentials using this. Dynamic credentials override existing credentials.
	Credentials []*UpdateAssistantDtoCredentialsItem `json:"credentials,omitempty" url:"-"`
	// This is a set of actions that will be performed on certain events.
	Hooks []*AssistantHookCallEnding `json:"hooks,omitempty" url:"-"`
	// This is the name of the assistant.
	//
	// This is required when you want to transfer between assistants in a call.
	Name *string `json:"name,omitempty" url:"-"`
	// This is the message that the assistant will say if the call is forwarded to voicemail.
	//
	// If unspecified, it will hang up.
	VoicemailMessage *string `json:"voicemailMessage,omitempty" url:"-"`
	// This is the message that the assistant will say if it ends the call.
	//
	// If unspecified, it will hang up without saying anything.
	EndCallMessage *string `json:"endCallMessage,omitempty" url:"-"`
	// This list contains phrases that, if spoken by the assistant, will trigger the call to be hung up. Case insensitive.
	EndCallPhrases []string        `json:"endCallPhrases,omitempty" url:"-"`
	CompliancePlan *CompliancePlan `json:"compliancePlan,omitempty" url:"-"`
	// This is for metadata you want to store on the assistant.
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"-"`
	// This is the plan for analysis of assistant's calls. Stored in `call.analysis`.
	AnalysisPlan *AnalysisPlan `json:"analysisPlan,omitempty" url:"-"`
	// This is the plan for artifacts generated during assistant's calls. Stored in `call.artifact`.
	//
	// Note: `recordingEnabled` is currently at the root level. It will be moved to `artifactPlan` in the future, but will remain backwards compatible.
	ArtifactPlan *ArtifactPlan `json:"artifactPlan,omitempty" url:"-"`
	// This is the plan for static predefined messages that can be spoken by the assistant during the call, like `idleMessages`.
	//
	// Note: `firstMessage`, `voicemailMessage`, and `endCallMessage` are currently at the root level. They will be moved to `messagePlan` in the future, but will remain backwards compatible.
	MessagePlan *MessagePlan `json:"messagePlan,omitempty" url:"-"`
	// This is the plan for when the assistant should start talking.
	//
	// You should configure this if you're running into these issues:
	// - The assistant is too slow to start talking after the customer is done speaking.
	// - The assistant is too fast to start talking after the customer is done speaking.
	// - The assistant is so fast that it's actually interrupting the customer.
	StartSpeakingPlan *StartSpeakingPlan `json:"startSpeakingPlan,omitempty" url:"-"`
	// This is the plan for when assistant should stop talking on customer interruption.
	//
	// You should configure this if you're running into these issues:
	// - The assistant is too slow to recognize customer's interruption.
	// - The assistant is too fast to recognize customer's interruption.
	// - The assistant is getting interrupted by phrases that are just acknowledgments.
	// - The assistant is getting interrupted by background noises.
	// - The assistant is not properly stopping -- it starts talking right after getting interrupted.
	StopSpeakingPlan *StopSpeakingPlan `json:"stopSpeakingPlan,omitempty" url:"-"`
	// This is the plan for real-time monitoring of the assistant's calls.
	//
	// Usage:
	// - To enable live listening of the assistant's calls, set `monitorPlan.listenEnabled` to `true`.
	// - To enable live control of the assistant's calls, set `monitorPlan.controlEnabled` to `true`.
	//
	// Note, `serverMessages`, `clientMessages`, `serverUrl` and `serverUrlSecret` are currently at the root level but will be moved to `monitorPlan` in the future. Will remain backwards compatible
	MonitorPlan *MonitorPlan `json:"monitorPlan,omitempty" url:"-"`
	// These are the credentials that will be used for the assistant calls. By default, all the credentials are available for use in the call but you can provide a subset using this.
	CredentialIds []string `json:"credentialIds,omitempty" url:"-"`
	// This is where Vapi will send webhooks. You can find all webhooks available along with their shape in ServerMessage schema.
	//
	// The order of precedence is:
	//
	// 1. assistant.server.url
	// 2. phoneNumber.serverUrl
	// 3. org.serverUrl
	Server          *Server          `json:"server,omitempty" url:"-"`
	KeypadInputPlan *KeypadInputPlan `json:"keypadInputPlan,omitempty" url:"-"`
}
